In [84]:
#| default_exp utilities.sparse

# utilities.sparse

> Extra functionality for [sparse](https://sparse.pydata.org) and [scipy.sparse](https://docs.scipy.org/doc/scipy/reference/sparse.html)

In [85]:
#| hide
from fastcore.test import test_eq
from pylgs.utilities.testing import test_array

In [86]:
#| export
import itertools as it

from fastcore.meta import delegates

import numpy as np
from numpy import array, ndarray
import scipy.sparse as sps
from scipy.sparse import sparray
import scipy.linalg as spl
import scipy.sparse.linalg as spa
from sparse import COO, GCXS, SparseArray
import sparse as ss

### sparse -

In [87]:
#|export
def sparse2d(a):
    """Create a 2D sparse array in specified format."""
    if isinstance(a, SparseArray): a = a.to_scipy_sparse()
    return sps.csr_array(a)

In [88]:
arrays = [np.identity(2), sps.eye(2), ss.eye(2), ss.eye(2, format='gcxs')]
[sparse2d(args) for args in arrays]

[<Compressed Sparse Row sparse array of dtype 'float64'
 	with 2 stored elements and shape (2, 2)>,
 <Compressed Sparse Row sparse array of dtype 'float64'
 	with 2 stored elements and shape (2, 2)>,
 <Compressed Sparse Row sparse array of dtype 'float64'
 	with 2 stored elements and shape (2, 2)>,
 <Compressed Sparse Row sparse array of dtype 'float64'
 	with 2 stored elements and shape (2, 2)>]

In [89]:
#|hide
test_eq([a.__class__.__name__ for a in _], ['csr_array', 'csr_array', 'csr_array', 'csr_array'])

In [90]:
#|export
@delegates(COO, but='data')
def sparse(a, format='coo', shape=None, **kwargs)->SparseArray:
    """Create an N-D sparse array in specified format."""
    if format == 'gcxs': cls = GCXS
    elif format == 'coo': cls = COO
    if isinstance(a, ndarray): return cls.from_numpy(a)
    if sps.issparse(a): return cls.from_scipy_sparse(a)
    if isinstance(a, SparseArray): return cls(a)
    # Assume a is coords and data in COO format
    if shape is None: shape = [max(c) - min(c) + 1 for c in a[0]]
    return cls(COO(*a, shape=shape, **kwargs))

In [91]:
arrays = [np.identity(2), sps.eye(2), ss.eye(2), [[[0, 1], [0, 1]], [1., 1.]]]
[sparse(*args) for args in it.product(arrays, ['coo', 'gcxs'])]

[<COO: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0>,
 <GCXS: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0, compressed_axes=(np.int64(0),)>,
 <COO: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0>,
 <GCXS: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0, compressed_axes=(0,)>,
 <COO: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0>,
 <GCXS: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0, compressed_axes=(np.int64(0),)>,
 <COO: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0>,
 <GCXS: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0, compressed_axes=(np.int64(0),)>]

In [92]:
#|hide
test_eq([a.__class__.__name__ for a in _], ['COO', 'GCXS', 'COO', 'GCXS', 'COO', 'GCXS', 'COO', 'GCXS'])

### sparse_identity -

In [93]:
#|export
def sparse2d_identity(n):
    return sps.eye_array(n)

In [94]:
sparse2d_identity(2)

<DIAgonal sparse array of dtype 'float64'
	with 2 stored elements (1 diagonals) and shape (2, 2)>

In [95]:
#|export
def sparse_identity(n, format='coo')->SparseArray:
    return ss.eye(n, format=format)

In [96]:
[sparse_identity(2, format=fmt) for fmt in ['coo', 'gcxs']]

[<COO: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0>,
 <GCXS: shape=(2, 2), dtype=float64, nnz=2, fill_value=0.0, compressed_axes=(np.int64(0),)>]

### sparse_diag -

In [97]:
#|export
def sparse2d_diag(diags, offsets=0):
    return sps.diags_array(diags, offsets=offsets)

In [98]:
sparse2d_diag([1, 1])

<DIAgonal sparse array of dtype 'float64'
	with 2 stored elements (1 diagonals) and shape (2, 2)>

In [99]:
#| export
def sparse_diag(diag, format='coo')->SparseArray:
    return sparse(sparse2d_diag(diag), format=format)

In [100]:
sparse_diag([1, 1])

Format,coo
Data Type,float64
Shape,"(2, 2)"
nnz,2
Density,0.5
Read-only,True
Size,32
Storage ratio,1.00


### sparse_toeplitz -

In [101]:
#| export
def dense_toeplitz(
    diags:ndarray, # Value on each diagonal, starting at lower left.
):
    """Return a toeplitz array given the value on each diagonal (starting at lower left)."""
    n = (len(diags) - 1) // 2
    return spl.toeplitz(diags[:n+1][::-1], diags[n:])

In [102]:
dense_toeplitz([1, 2, 3])

array([[2, 3],
       [1, 2]])

In [103]:
#| export
def sparse_toeplitz(
    diags:ndarray, # Value on each diagonal, starting at lower left.
    format='coo'
)->SparseArray:
    """Return a toeplitz sparse array in specified format given the value on each diagonal (starting at lower left)."""
    return sparse(dense_toeplitz(diags), format=format)

In [104]:
sparse_toeplitz([1, 2, 3, 4, 5])

Format,coo
Data Type,int64
Shape,"(3, 3)"
nnz,9
Density,1.0
Read-only,True
Size,216
Storage ratio,3.00


In [105]:
_.todense()

array([[3, 4, 5],
       [2, 3, 4],
       [1, 2, 3]])

In [106]:
#| hide
test_array('utilities', 'sparse_toeplitz', _)

In [107]:
#| export
def sparse2d_kronecker_matrix(n, k=0):
    """The nxn sparse kronecker matrix delta_(i,j-k) in specified format."""
    return sparse2d_diag(np.ones(n - abs(k)), offsets=k)

In [108]:
sparse2d_kronecker_matrix(3, 2)

<DIAgonal sparse array of dtype 'float64'
	with 1 stored elements (1 diagonals) and shape (3, 3)>

In [109]:
_.todense()

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [110]:
#| export
def sparse_kronecker_matrix(n, k=0, format='coo')->SparseArray:
    """The nxn sparse kronecker matrix delta_(i,j-k) in specified format."""
    return sparse(sparse2d_kronecker_matrix(n, k), format=format)

In [111]:
sparse_kronecker_matrix(3, 2)

Format,coo
Data Type,float64
Shape,"(3, 3)"
nnz,1
Density,0.1111111111111111
Read-only,True
Size,16
Storage ratio,0.22


In [112]:
#| hide
test_array('utilities', 'sparse_kron', _)

In [113]:
#| export 
def kron(a, b, *rest):
    if not rest: 
        if sps.issparse(a) and sps.issparse(b): return sps.kron(a, b, format='csr')
        return np.kron(a, b)
    return kron(kron(a, b), *rest)

In [114]:
kron(np.eye(2), np.eye(2), np.eye(2))

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [115]:
#| hide
test_array('utilities', 'kron_1', _)

In [116]:
kron(*[sparse2d_identity(2)] * 3)

<Compressed Sparse Row sparse array of dtype 'float64'
	with 8 stored elements and shape (8, 8)>

In [117]:
#| hide
test_array('utilities', 'kron_1', _.todense())

### sparse2d_rand -

In [118]:
#|export
sparse2d_rand = sps.random_array

In [119]:
sparse2d_rand([2, 3])

<COOrdinate sparse array of dtype 'float64'
	with 0 stored elements and shape (2, 3)>

### spilu -

In [120]:
#|export
spilu = spa.spilu

### restrict_bandwidth -

In [121]:
#| export
def restrict_bandwidth(a_sparray:sparray, width):
    """Make a scipy sparse array banded by setting all elements outside the bandwidth to zero."""
    result = a_sparray.copy()
    i, j = result.nonzero()
    result.data[np.abs(i - j) > width] = 0.
    result.eliminate_zeros()
    return result

In [122]:
restrict_bandwidth(sps.csr_array(np.ones((5, 5))), 1)

<Compressed Sparse Row sparse array of dtype 'float64'
	with 13 stored elements and shape (5, 5)>

In [123]:
_.toarray()

array([[1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [124]:
#| hide
test_array('utilities', 'restrict_bandwidth', _)

## Export -

In [125]:
#| hide
import nbdev; nbdev.nbdev_export()

<unknown>:1: SyntaxWarning: invalid escape sequence '\('
<unknown>:1: SyntaxWarning: invalid escape sequence '\('
<unknown>:1: SyntaxWarning: invalid escape sequence '\('
<unknown>:1: SyntaxWarning: invalid escape sequence '\('
