In [465]:
#| default_exp pymor.operators

# pymor.operators

> Extended functionality for [pyMOR](https://pymor.org/) operators

In [466]:
#| export
from __future__ import annotations
from pathlib import Path
import importlib
from numbers import Number
import math
from functools import reduce

from fastcore.basics import patch
from fastcore.meta import delegates
from pydash import unzip

import numpy as np
from numpy import array, ndarray
from scipy.sparse import issparse, sparray
from sparse import SparseArray
import sympy as sy
import pandas as pd
from xarray import DataArray, Coordinates

from pymor.basic import LincombOperator, NumpyMatrixOperator, ZeroOperator, ExpressionParameterFunctional, NumpyVectorSpace, Mu, IdentityOperator
from pymor.models.interface import Model
from pymor.algorithms.to_matrix import to_matrix, ToMatrixRules
from pymor.algorithms.simplify import ExpandRules, expand, ContractRules, contract
from pymor.algorithms.rules import match_class, RuleTable
from pymor.algorithms.lincomb import assemble_lincomb
from pymor.operators.interface import Operator
from pymor.core.base import abstractmethod
from pymor.operators.interface import Operator
from pymor.parameters.functionals import ParameterFunctional

from pylgs.patches import *
from pylgs.utilities.xarray import *
from pylgs.utilities.sparse import sparse, sparse2d, kron, sparse2d_rand
from pylgs.pymor.parameters import *
from pylgs.pymor.vectorarrays import *
from pylgs.pymor.vectorarrays import _unlabel_dims

In [467]:
# | hide
from fastcore.test import test_eq, test_close
from pylgs.utilities.testing import test_array

In [468]:
from IPython.display import HTML

In [469]:
# HTML('''<style>
# html,body,address,blockquote,div,form,fieldset,caption,h1,h2,h3,h4,h5,h6,hr,ul,ol,ul,li,table,tr,td,th,p,img {margin:0; padding:0;}
# ul, ol, li {list-style-type: none;}
# img,fieldset{border: none;}
# ul {margin-left: -2em}
# </style>''')

In [470]:
# HTML('''foo<ul><li>foo</li></ul>foo''')

In [471]:
#|export
LincombOperator.suboperator_symbol = '+'

In [472]:
#|export
def _mapping_str(op:Operator):
    try:
        return f"{op.source._repr_html_()} → {op.range._repr_html_()}"
    except AttributeError:
        return f"{str(op.source)} → {str(op.range)}"

In [473]:
#|export
def _operator_group_tag(
    level:int, 
    cls:str, 
    mapping:str, 
    name:str|None=None,
    contents:str|None=None,
    suboperators:list(str)|None=None, 
    symbol:str|None=None, 
    opened:bool=False
) -> str:
    if suboperators or contents:
        return f'''
            <li>
                <details {'open' if opened else 'closed'}>
                    <summary>
                        <ul class="operator">
                            {'<li>' + name + '</li>' if name else ''}
                            <li>{cls}</li>
                            <li>{mapping}</li>
                        </ul>
                    </summary>
                    <ul class="operator-group operator-group-{'even' if not (level % 2) else 'odd'}">
                        {contents or symbol.join(suboperators)}
                    </ul>
                </details>
            </li>
        '''
    else:
        return f'''
            <li>
                <ul class="operator">
                    {'<li>' + name + '</li>' if name else ''}
                    <li>{cls}</li>
                    <li>{mapping}</li>
                </ul>
            </li>
        '''

In [474]:
#|export
def _operator_html_node(op:Operator, level:int=0, opened:bool=False) -> str:
    cls = op.__class__.__name__
    name = op.name if op.name != cls else None
    mapping = _mapping_str(op)
    contents = None
    if hasattr(op, 'operators'):
        suboperators = [_operator_html_node(o, level=level + 1, opened=opened) for o in op.operators]
        symbol = op.suboperator_symbol
        return _operator_group_tag(level, cls, mapping, name, contents, suboperators, symbol, opened)
    if hasattr(op, 'matrix'):
        contents = op.matrix._repr_html_() if hasattr(op.matrix, '_repr_html_') else str(op.matrix)
        return _operator_group_tag(level, cls, mapping, name, contents)
    return _operator_group_tag(level, cls, mapping, name)

In [475]:
#|export
def operator_html_tree(op:Operator, opened:bool=False) -> str:
    style = """
    <style>
        .operator-group summary {
            list-style: none;
            display: flex;
            gap: 0.25em;
            align-items: start;
            cursor: pointer;
        }
        .operator-group summary::before {
            content: '▶︎';
            font-size: 75%;
            align-items: center;
            width: 1em;
            flex-shrink: 0;
            transition: 0.3s;
        }
        .operator-group details[open] > summary::before {
            transform: rotate(90deg);
            transform-origin: 40% 45% 0;
        }
        .operator-group-odd > li {
            background-color: #f0f0f0;;
        }
        .operator-group-even > li {
            background-color: #fbfbfb;
        }
        .operator-group {
            display: flex;
            gap: .4em;
            align-items: center;
            padding: 0px;
            margin-left: -2em;
            margin-top: .25em;
        }
        .operator-group > li {
            list-style-type: none;
            border: 1px solid black;
            border-radius: .25em;
            padding: .25em;
        }
        .operator {
            margin: 0;
            padding: 0;
            margin-top: -.2em;
            margin-left: -2em;
        }
        .operator > li {
            list-style-type: none;
            border: none;
            padding: 0;
            line-height: 1.25em;
        }
    </style>
    """
    return style + f'<ul class="operator-group operator-group-odd">{_operator_html_node(op, opened=opened)}</ul>'

In [476]:
op = LincombOperator(
    [
        NumpyMatrixOperator(np.ones([1])), 
        LincombOperator([NumpyMatrixOperator(np.ones([1]))] * 2, [.1] * 2)
    ],
    [1.] * 2
)
HTML(operator_html_tree(op, True))

In [477]:
#|export
@patch
def _repr_html_(self:Operator):
    return operator_html_tree(self)

In [478]:
NumpyMatrixOperator(np.ones([1]))

NumpyMatrixOperator(<1x1 dense>)

In [479]:
op

LincombOperator(
    (NumpyMatrixOperator(<1x1 dense>),
     LincombOperator((NumpyMatrixOperator(<1x1 dense>), NumpyMatrixOperator(<1x1 dense>)), (0.1, 0.1))),
    (1.0, 1.0))

## XarrayMatrixOperator

`XarrayMatrixOperator` is a replacement for `NumpyMatrixOperator` that affords several advantages.

In [480]:
#| exporti
class XarrayMatrixBasedOperator(Operator):
    """Base class for operators that assemble into an `XarrayMatrixOperator`."""

    linear = True

    @property
    def H(self):
        if not self.parametric:
            return self.assemble().H
        else:
            return super().H

    @abstractmethod
    def assemble(self, mu=None): pass

    def apply(self, U, mu=None):
        return self.range.from_xarray(self.assemble(mu).matrix.dot(U.impl._array))

    def apply_adjoint(self, V, mu=None):
        return self.assemble(mu).apply_adjoint(V)

    def as_range_array(self, mu=None):
        matrix = _unlabel_dims(self.assemble(mu).matrix.squeeze())
        extended_coords = {d: matrix.coords[d] for d in matrix.dims if d not in self.range.dims}
        return self.range.from_numpy(self.matrix.data, extended_coords)

    def as_source_array(self, mu=None):
        matrix = _unlabel_dims(self.assemble(mu).matrix.squeeze())
        extended_coords = {d: matrix.coords[d] for d in matrix.dims if d not in self.source.dims}
        return self.source.from_numpy(self.matrix.data, extended_coords).conj()

    @property
    def display_name(self):
        return self.name if self.name != self.__class__.__name__ else 'X'

    def __str__(self):
        return f"{self.display_name}{_mapping_str(self)}"

### _ndims -


In [481]:
#| export
def _ndims(matrix):
    if isinstance(matrix, DataArray):
        return len(matrix.dims)
    else:
        return matrix.ndim    

### _get_space_dims -


In [482]:
# #| export
# def _get_space_dims(dims, matrix, default):
#     if dims is None:
#         if hasattr(matrix, 'dims'): return list(matrix.dims)
#         else: return [default]
#     elif isinstance(dims, str): return [dims]
#     elif hasattr(dims, 'dims'): return dims.dims
#     return list(dims)

### XarrayMatrixOperator -

In [483]:
#|export
def _label_dims_with(obj, lbl):
    if isinstance(obj, list | tuple): 
        return [d + lbl for d in obj]
    if isinstance(obj, Coordinates):
        return {k + lbl: v.data for k,v in obj.items()}

In [484]:
space_a = XarrayVectorSpace({'A': np.linspace(0, 1, 2)})

In [485]:
_label_dims_with(['A'], Lbl.SRC)

['A (source)']

In [486]:
_label_dims_with(space_a.coords, Lbl.SRC)

{'A (source)': array([0., 1.])}

In [487]:
#|export
def _label_dims(obj, src_dims, rng_dims):
    if isinstance(obj, XarrayVectorSpace):
        coords_data = [(_label_dims(dim, src_dims, rng_dims), data, attrs) for dim,data,attrs in obj.coords_data]
        return obj.with_(coords_data=coords_data)
    labled_src_dims = _label_dims_with(src_dims, Lbl.SRC)
    labled_rng_dims = _label_dims_with(rng_dims, Lbl.RNG)
    rename_dict = dict(zip(src_dims, labled_src_dims)) | dict(zip(rng_dims, labled_rng_dims))
    match obj:
        case str():
            return rename_dict.get(obj, obj)
        case list() | tuple():
            return [rename_dict.get(dim, dim) for dim in obj]
        case DataArray():
            return obj.rename(rename_dict)
        case Coordinates():
            return Coordinates({rename_dict.get(k, k): v.data for k,v in obj.items()})

In [488]:
matrix = DataArray(
        np.arange(6).reshape(2, 3), 
        {'A': np.linspace(0, 1, 2), 'B': np.linspace(0, 1, 3)}
    )

In [489]:
matrix = _label_dims(matrix, ['A'], ['B'])
matrix

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [490]:
crds = _label_dims(space_a.coords, ['A'], ['B'])
crds

Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0

In [491]:
spc = _label_dims(space_a, ['A'], ['B'])
spc

XarrayVectorSpace(coords_data=[('A (source)', array([0., 1.]), {})])

In [492]:
matrix

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [493]:
_unlabel_dims('A (source)')

'A'

In [494]:
_unlabel_dims(matrix)

<xarray.DataArray (A: 2, B: 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A        (A) float64 16B 0.0 1.0
  * B        (B) float64 24B 0.0 0.5 1.0

In [495]:
_unlabel_dims(crds)

Coordinates:
  * A        (A) float64 16B 0.0 1.0

In [496]:
spc

XarrayVectorSpace(coords_data=[('A (source)', array([0., 1.]), {})])

In [497]:
_unlabel_dims(spc)

XarrayVectorSpace(coords_data=[('A', array([0., 1.]), {})])

In [498]:
#|export
def _is_labeled_da(da):
    if not isinstance(da, DataArray): return False
    return any(d.endswith(Lbl.SRC) or d.endswith(Lbl.RNG) for d in da.dims)

In [499]:
#|export
def coordinates_to_list(coords, dims):
    return [(d, coords[d].data, coords[d].attrs) for d in dims]

In [500]:
#| export
def _get_space_dims(dims):
    if dims is None: return None, None
    if hasattr(dims, 'dims'): return dims.dims, dims.coords
    if isinstance(dims, dict): dims = Coordinates(dims)
    if isinstance(dims, Coordinates): return list(dims), coords
    if isinstance(dims, str): dims = [dims]
    if isinstance(dims, list | tuple): return dims, None
    raise ValueError("Source or range specification not valid")

In [501]:
#| export
class XarrayMatrixOperator(XarrayMatrixBasedOperator):
    """An `Operator` backed by an xarray `DataArray`."""

    def __init__(
        self, 
        matrix:DataArray|ndarray|SparseArray|sparray, # N-dimensional matrix
        source:XarrayVectorSpace|Coordinates|dict|list|str=None, # Source vector space, coordinates, or dimension name(s)
        range:XarrayVectorSpace|Coordinates|dict|list|str=None, # Range vector space, coordinates, or dimension name(s)
        solver_options:dict=None, # Options for matrix solver
        name:str=None # Operator name
    ):
        if not source:
            if not _is_labeled_da(matrix):
                raise ValueError("Source argument required if matrix is not a DataArray with a dim labeled as source.")

        if issparse(matrix): matrix = sparse(matrix)
        src_dims, src_coords = _get_space_dims(source)
        rng_dims, rng_coords = _get_space_dims(range)
        if not isinstance(matrix, DataArray):
            if rng_coords is None:
                rng_coords = Coordinates({dim: np.arange(n) for dim, n in zip(rng_dims, matrix.shape)})
            if src_coords is None:
                src_coords = Coordinates({dim: np.arange(n) for dim, n in zip(src_dims, matrix.shape[len(rng_dims):])})
            labeled_src_dims = _label_dims_with(src_dims, Lbl.SRC)
            labeled_rng_dims = _label_dims_with(rng_dims, Lbl.RNG)
            labeled_src_coords = _label_dims_with(src_coords, Lbl.SRC)
            labeled_rng_coords = _label_dims_with(rng_coords, Lbl.RNG)
            matrix = DataArray(
                matrix, 
                dims=labeled_rng_dims + labeled_src_dims,
                coords=labeled_rng_coords | labeled_src_coords,
                name=name
            )
        elif not _is_labeled_da(matrix):
            rng_coords = Coordinates({k: matrix[k] for k in rng_dims})
            src_coords = Coordinates({k: matrix[k] for k in src_dims})
            matrix = _label_dims(matrix, src_dims, rng_dims)
        else:
            labeled_src_dims = [d for d in matrix.dims if d.endswith(Lbl.SRC)]
            labeled_rng_dims = [d for d in matrix.dims if d.endswith(Lbl.RNG)]
            src_dims = _unlabel_dims(labeled_src_dims)
            rng_dims = _unlabel_dims(labeled_rng_dims)
            labeled_src_coords = [(k, v.data, v.attrs) for k,v in matrix.coords.items() if k.endswith(Lbl.SRC)]
            labeled_rng_coords = [(k, v.data, v.attrs) for k,v in matrix.coords.items() if k.endswith(Lbl.RNG)]
            src_coords = _unlabel_dims(labeled_src_coords)
            rng_coords = _unlabel_dims(labeled_rng_coords)
        if name is None: name = matrix.name
        source = XarrayVectorSpace(src_coords)
        range = XarrayVectorSpace(rng_coords)
        self.__auto_init(locals())
        self.labeled_source = _label_dims(source, src_dims, [])
        self.labeled_range = _label_dims(range, [], rng_dims)

    def assemble(self, mu=None): return self

    @property
    def size(self):
        return self.matrix.size
        
    @property
    def sparse(self):
        return isinstance(self.matrix.data, SparseArray)

A pyMOR `Operator` maps a `VectorArray` from a source `VectorSpace` to another `VectorArray` in a range `VectorSpace`. The `XarrayMatrixOperator` acts on an `XarrayVectorArray` from an `XarrayVectorSpace` by means of multiplication by an xarray `DataArray`.

The `html` representation of an `XarrayMatrixOperator` is *operator name*{*source space*} → {*range space*}, where X is used as the name if the operator has not been given an explict name.

The matrix can be supplied as a `DataArray`, or as an unlabeled numpy `ndarray`, scipy.sparse `sparray`, or sparse `SparseArray`. 

Create from a numpy array and range and source names:

In [502]:
op = XarrayMatrixOperator(np.ones((2, 2)), source='A', range='B')
op

XarrayMatrixOperator(
    <xarray.DataArray (B (range): 2, A (source): 2)> Size: 32B
    array([[1., 1.],
           [1., 1.]])
    Coordinates:
      * B (range)   (B (range)) int64 16B 0 1
      * A (source)  (A (source)) int64 16B 0 1,
    source=XarrayVectorSpace(coords_data=[('A', array([0, 1]), {})]),
    range=XarrayVectorSpace(coords_data=[('B', array([0, 1]), {})]))

The `DataArray` backing the `Operator` is stored in the `matrix` attribute:

In [503]:
op.matrix

<xarray.DataArray (B (range): 2, A (source): 2)> Size: 32B
array([[1., 1.],
       [1., 1.]])
Coordinates:
  * B (range)   (B (range)) int64 16B 0 1
  * A (source)  (A (source)) int64 16B 0 1

The `source` and `range` attributes store the corresponding `VectorArray`s:

In [504]:
op.source

XarrayVectorSpace(coords_data=[('A', array([0, 1]), {})])

In [505]:
op.range

XarrayVectorSpace(coords_data=[('B', array([0, 1]), {})])

Create from a numpy array and specified range and source spaces:

In [506]:
space_a = XarrayVectorSpace({'A': np.linspace(0, 1, 2)})
space_b = XarrayVectorSpace({'B': ['c', 'd', 'e']})
XarrayMatrixOperator(np.arange(6).reshape(2, 3), source=space_b, range=space_a, name='foo')

XarrayMatrixOperator(
    <xarray.DataArray 'foo' (A (range): 2, B (source): 3)> Size: 48B
    array([[0, 1, 2],
           [3, 4, 5]])
    Coordinates:
      * A (range)   (A (range)) float64 16B 0.0 1.0
      * B (source)  (B (source)) <U1 12B 'c' 'd' 'e',
    source=XarrayVectorSpace(coords_data=[('B', array(['c', 'd', 'e'], dtype='<U1'), {})]),
    range=XarrayVectorSpace(coords_data=[('A', array([0., 1.]), {})]),
    name='foo')

In [507]:
_.matrix

<xarray.DataArray 'foo' (A (range): 2, B (source): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (range)   (A (range)) float64 16B 0.0 1.0
  * B (source)  (B (source)) <U1 12B 'c' 'd' 'e'

Create from a `DataArray` with defined coords:

In [508]:
op = XarrayMatrixOperator(
    DataArray(
        np.arange(6).reshape(2, 3), 
        {'A': np.linspace(0, 1, 2), 'B': np.linspace(0, 1, 3)}
    ),
    source=['A'],
    range=['B'],
)
op

XarrayMatrixOperator(
    <xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
    array([[0, 1, 2],
           [3, 4, 5]])
    Coordinates:
      * A (source)  (A (source)) float64 16B 0.0 1.0
      * B (range)   (B (range)) float64 24B 0.0 0.5 1.0,
    source=XarrayVectorSpace(coords_data=[('A', array([0., 1.]), {})]),
    range=XarrayVectorSpace(coords_data=[('B', array([0. , 0.5, 1. ]), {})]))

In [509]:
op.matrix

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [510]:
op.range

XarrayVectorSpace(coords_data=[('B', array([0. , 0.5, 1. ]), {})])

In [511]:
op = XarrayMatrixOperator(sparse2d_rand([4, 5], density=.5, random_state=42), source='A', range='B')
op

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


In [512]:
op.matrix

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


### H -


In [513]:
#| export
@patch(as_prop=True)
def H(self:XarrayMatrixOperator):
    """The adjoint operator."""
    adjoint_matrix = self.matrix if np.isrealobj(self.matrix) else self.matrix.conj()           
    options = {'inverse': self.solver_options.get('inverse_adjoint'),
               'inverse_adjoint': self.solver_options.get('inverse')} if self.solver_options else None
    return self.with_(matrix=_unlabel_dims(adjoint_matrix), source=self.range, range=self.source, 
                      solver_options=options, name=self.name + '_adjoint')

In [514]:
op

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


In [515]:
op.H

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


### apply -


In [516]:
#|export
def contract_matvec(a, b, axes):
    """Contract one axis of the first (2D) array with one axis of the second (ND) array."""
    return np.moveaxis(np.tensordot(a, b, axes), 0, axes[1])

In [517]:
contract_matvec(np.ones([2,5]), np.ones([4,5,6]), [1, 1]).shape

(4, 2, 6)

In [518]:
contract_matvec(np.ones([6,2]), np.ones([4,5,6]), [0, 2]).shape

(4, 5, 2)

In [519]:
#|export
def dims_matvec(a, b):
    """Contract one axis of the first (2D) array with the axis of the second (ND) array of the same name."""
    a, adims = a
    b, bdims = b
    ax = [[adims.index(d), i] for i,d in enumerate(bdims) if d in adims][0]
    newdims = list(bdims)
    newdims[ax[1]] = adims[1 - ax[0]]
    return contract_matvec(a, b, ax), newdims

In [520]:
dims_matvec([np.ones([2,5]), ["A", "B"]], [np.ones([4,5,6]), ["C", "B", "D"]])

(array([[[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]],
 
        [[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]],
 
        [[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]],
 
        [[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]]]),
 ['C', 'A', 'D'])

In [521]:
#| export
@patch
def __truediv__(self:XarrayVectorSpace, other):
    if not isinstance(other, XarrayVectorSpace): raise NotImplementedError
    return self.with_(coords={k: v for k,v in self.coords.items() if k not in other.coords})

In [522]:
#| export
@patch
def range_under(self:XarrayVectorSpace, op:XarrayMatrixOperator):
    """Find the space that this space is mapped to by an XarrayMatrixOperator. Assumes that the operator has one-dimensional source and range."""
    if not op.range.dims:
        coords = self.coords_data.copy()[:-1]
    else:
        source_dim = op.source.dims[0]
        range_dim = op.range.dims[0]
        range_coord = op.range.coords[range_dim]
        range_coord = (range_coord.name, range_coord.data, range_coord.attrs)
        coords = [range_coord if c[0] == source_dim else c for c in self.coords_data]
    return self.with_(coords_data=coords)

In [523]:
U = op.source.zeros({'len': [0]})

In [524]:
U.space.range_under(op)

XarrayVectorSpace(coords_data=[('B', array([0, 1, 2, 3]), {})])

In [525]:
#| export
@patch
def apply(
    self:XarrayMatrixOperator, 
    U, # `XarrayVectorArray` of vectors to which the operator is applied
    mu=None # The parameter values for which to evaluate the operator
)->XarrayVectorArray: # `XarrayVectorArray` in the range `XarrayVectorSpace`
    """Apply the operator to an `XarrayVectorArray` in the source vector space."""
    # src_dims = _label_dims(U.array.dims, U.dims, [])
    # out, out_dims = dims_matvec((self.matrix.data, self.matrix.dims), (U.array.data, src_dims))
    # out = self.range.from_numpy(out, extended_dim=U.extended_coords)
    out = U.space.range_under(self).from_xarray(_unlabel_dims(self.matrix.dot(U.array_labeled_as_source())))
    if self.name != self.__class__.__name__: out.name = self.name
    return out

In [526]:
U = op.source.zeros({'len': [0]})
op.apply(U)

XarrayVectorArray(
    XarrayVectorSpace(coords_data=[('B', array([0, 1, 2, 3]), {})]),
    XarrayVectorArrayImpl(
        array([[0., 0., 0., 0.]]),
        XarrayVectorSpace(coords_data=[('B', array([0, 1, 2, 3]), {})]),
        _data_dims=['len', 'B'],
        _extended_coords_data=[('len', array([0]), {})]),
    _len=1)

### apply_adjoint -

In [527]:
#| export
@patch
def apply_adjoint(
    self:XarrayMatrixOperator, 
    V, # `XarrayVectorArray` of vectors to which the operator is applied
    mu=None # The parameter values for which to evaluate the operator
)->XarrayVectorArray: # `XarrayVectorArray` in the source `XarrayVectorSpace`
    """Apply the adjoint of the operator to an `XarrayVectorArray` in the range vector space."""
    return self.H.apply(V, mu=mu)

In [528]:
V = op.range.zeros({'len': [0]})

In [529]:
op.apply_adjoint(V)

XarrayVectorArray(
    XarrayVectorSpace(coords_data=[('A', array([0, 1, 2, 3, 4]), {})]),
    XarrayVectorArrayImpl(
        array([[0., 0., 0., 0., 0.]]),
        XarrayVectorSpace(coords_data=[('A', array([0, 1, 2, 3, 4]), {})]),
        _data_dims=['len', 'A'],
        _extended_coords_data=[('len', array([0]), {})]),
    _len=1)

### _assemble_lincomb -

In [530]:
#| export
@patch
def _assemble_lincomb(self:XarrayMatrixOperator, operators, coefficients, identity_shift=0., solver_options=None, name=None):
    if not all(isinstance(op, XarrayMatrixOperator) for op in operators):
        return None

    common_mat_dtype = reduce(np.promote_types,
                              (op.matrix.dtype for op in operators if hasattr(op, 'matrix')))
    common_coef_dtype = reduce(np.promote_types, (type(c) for c in coefficients + [identity_shift]))
    common_dtype = np.promote_types(common_mat_dtype, common_coef_dtype)

    if coefficients[0] == 1:
        matrix = operators[0].matrix.astype(common_dtype)
    else:
        matrix = operators[0].matrix * coefficients[0]
        if matrix.dtype != common_dtype:
            matrix = matrix.astype(common_dtype)

    for op, c in zip(operators[1:], coefficients[1:]):
        if c == 1:
            try:
                matrix += op.matrix
            except NotImplementedError:
                matrix = matrix + op.matrix
        elif c == -1:
            try:
                matrix -= op.matrix
            except NotImplementedError:
                matrix = matrix - op.matrix
        else:
            try:
                matrix += (op.matrix * c)
            except NotImplementedError:
                matrix = matrix + (op.matrix * c)

    if identity_shift: raise NotImplementedError

    return XarrayMatrixOperator(matrix, source=self.source, range=self.range, solver_options=solver_options)

In [531]:
#| hide
LincombOperator([op, op], [.3, .456]).assemble().matrix.data.todense()

array([[5.88746976e-04, 0.00000000e+00, 5.34212675e-03, 0.00000000e+00,
        7.36159172e-01],
       [4.62409789e-01, 1.74351933e-02, 0.00000000e+00, 0.00000000e+00,
        7.50111939e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.52792414e-02],
       [3.02294895e-01, 0.00000000e+00, 3.96729643e-01, 4.66816021e-01,
        0.00000000e+00]])

### to_matrix_XarrayMatrixOperator -


In [532]:
#| exporti
@match_class(XarrayMatrixOperator)
def to_matrix_XarrayMatrixOperator(self, op):
    """Return the operator as a 2D matrix with stacked range and source dimensions in either `ndarray` or `sparray` format."""
    data = op.matrix.stack(_range=op.labeled_range.coords.dims, _source=op.labeled_source.coords.dims).data
    if isinstance(data, SparseArray): return sparse2d(data)
    return data
    
ToMatrixRules.insert_rule(-1, to_matrix_XarrayMatrixOperator)

In [533]:
#| hide
to_matrix(op)

<Compressed Sparse Row sparse array of dtype 'float64'
	with 10 stored elements and shape (4, 5)>

In [534]:
#| export
@patch
def to_numpy(self:XarrayMatrixOperator):
    """Return the operator in dense `ndarray` format."""
    return self.matrix.to_numpy()

The returned numpy array will be of shape $r_1\times \ldots \times r_n \times s_1 \times \ldots \times s_m$ where $r_i$ are the dimensions of the $n$ vector spaces making up the range product vector space, and $s_j$ are the dimensions of the $m$ vector spaces making up the source product vector space.

In [535]:
op.to_numpy()

array([[7.78765841e-04, 0.00000000e+00, 7.06630522e-03, 0.00000000e+00,
        9.73755519e-01],
       [6.11653160e-01, 2.30624250e-02, 0.00000000e+00, 0.00000000e+00,
        9.92211559e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.66656632e-02],
       [3.99860972e-01, 0.00000000e+00, 5.24774660e-01, 6.17481510e-01,
        0.00000000e+00]])

### densify -


In [536]:
#| exporti
class DensifyRules(RuleTable):
    """|RuleTable| for the :func:`densify` algorithm."""

    def __init__(self):
        super().__init__(use_caching=True)

    @match_class(XarrayMatrixOperator)
    def action_XarrayMatrixOperator(self, op):
        op = self.replace_children(op)
        if op.sparse:
            matrix = op.matrix.copy()
            matrix.data = matrix.data.todense()
            op = op.with_(matrix=matrix)
        return op
    
    @match_class(Model, Operator)
    def action_recurse(self, op):
        return self.replace_children(op)

In [537]:
#| export
def densify(
    obj:Model|Operator # Object to densify
)->Model|Operator: # Densified object
    """Convert sparse operators to dense."""
    return DensifyRules().apply(obj)

An operator backed by a sparse `DataArray`:

In [538]:
op.sparse

True

Convert the operator to one backed by a dense `DataArray`:

In [539]:
densify(op).sparse

False

In [540]:
#|hide
test_eq(_, False)

## XarrayFunctionalOperator

In [541]:
#| export
class XarrayFunctionalOperator(XarrayMatrixBasedOperator):
    """An `Operator` described by a `ParameterFunctional` that assembles to a `XarrayMatrixOperator`."""
    
    def __init__(self, functional:ParameterFunctional, range, source):
        self.__auto_init(locals())

    def assemble(self, mu=None): 
        return XarrayMatrixOperator(self.functional.evaluate(mu), range=self.range, source=self.source)

    @property
    def size(self):
        return self.matrix.size

## IdentityOperator

In [542]:
# @patch
# def apply(self:IdentityOperator, U, mu=None):
#     if isinstance(U, XarrayVectorArray):

# space_a = XarrayVectorSpace({'A (source)': np.linspace(0, 1, 2)})
# space_b = XarrayVectorSpace({'B': ['c', 'd', 'e']})

# space_a * space_b

# space

# IdentityOperator(space).source.dims

## SumOperator

In [543]:
#| export
class SumOperator(Operator):
    """An `Operator` that sums over one or more dimensions of a `XarrayVectorSpace`."""
    
    linear = True
    
    def __init__(
        self, 
        source_coords:Coordinates|dict, # Coordinates to sum over 
        name=None # Operator name
    ):
        self.__auto_init(locals())
        self.source = XarrayVectorSpace(source_coords)
        self.range = XarrayVectorSpace()

    def assemble(self, mu=None): return self

    def apply(self, U, mu=None):
        U = self.range.from_xarray(U.array.sum(self.source.dims))
        if self.name != self.__class__.__name__: U.name = self.name
        return U

    def __mul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([self, other])
        return super().__mul__(other)

    def __rmul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([other, self])
        return super().__mul__(other)

    def __str__(self):
        return f"{self.name if self.name != self.__class__.__name__ else '∑'}{_mapping_str(self)}"

In [544]:
space = XarrayVectorSpace({'A': [1, 2], 'B': ['a', 'b', 'c']}, name='foo')

In [545]:
np.random.seed(42)
U = space.from_numpy(np.random.rand(space.dim))

In [546]:
U.array.A

<xarray.DataArray 'A' (A: 2)> Size: 16B
array([1, 2])
Coordinates:
  * A        (A) int64 16B 1 2

In [547]:
op = SumOperator(U.array.A)
op

SumOperator(
    <xarray.DataArray 'A' (A: 2)> Size: 16B
    array([1, 2])
    Coordinates:
      * A        (A) int64 16B 1 2)

In [548]:
op.source

XarrayVectorSpace(coords_data=[('A', array([1, 2]), {})], name='A')

In [549]:
op.range

XarrayVectorSpace(coords_data=[])

In [550]:
op.apply(U).array

<xarray.DataArray (B: 3)> Size: 24B
array([0.9731986 , 1.10673295, 0.88798846])
Coordinates:
  * B        (B) <U1 12B 'a' 'b' 'c'

## ScaleOperator

In [551]:
#| export
class ScaleOperator(Operator):
    """A scaling operator for `XarrayVectorSpace`s."""
    
    def __init__(self, array, space=None, name=None):
        if not isinstance(array, DataArray): array = DataArray(array, coords=space.coords, name=name)
        if space is None: space = XarrayVectorSpace(array)
        self.__auto_init(locals())
        self.source = space
        self.range = space

    def assemble(self, mu=None): return self

    def apply(self, U, mu=None):
        U = U * self.array
        if self.name != self.__class__.__name__: U.name = self.name
        return U

    @property
    def display_name(self):
        return self.name if self.name != self.__class__.__name__ else 'S'
    
    def __mul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([self, other])
        return super().__mul__(other)

    def __rmul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([other, self])
        return super().__mul__(other)

    def __str__(self):
        return f"{self.display_name}{_mapping_str(self)}"

In [552]:
space = XarrayVectorSpace({'A': [1, 2], 'B': ['a', 'b', 'c']}, name='foo')

In [553]:
U = space.from_numpy(np.arange(6))

In [554]:
U.array

<xarray.DataArray (A: 2, B: 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A        (A) int64 16B 1 2
  * B        (B) <U1 12B 'a' 'b' 'c'

In [555]:
arr = U.array[0].drop_vars('A')
arr

<xarray.DataArray (B: 3)> Size: 24B
array([0, 1, 2])
Coordinates:
  * B        (B) <U1 12B 'a' 'b' 'c'

In [556]:
scale_op = ScaleOperator(arr, name='bar')
scale_op

ScaleOperator(
    <xarray.DataArray (B: 3)> Size: 24B
    array([0, 1, 2])
    Coordinates:
      * B        (B) <U1 12B 'a' 'b' 'c',
    space=XarrayVectorSpace(coords_data=[('B', array(['a', 'b', 'c'], dtype='<U1'), {})]),
    name='bar')

In [557]:
scale_op.apply(U)

XarrayVectorArray(
    XarrayVectorSpace(coords_data=[('A', [1, 2], {}), ('B', ['a', 'b', 'c'], {})], name='foo'),
    XarrayVectorArrayImpl(
        array([[ 0,  1,  4], [ 0,  4, 10]]),
        XarrayVectorSpace(coords_data=[('A', [1, 2], {}), ('B', ['a', 'b', 'c'], {})], name='foo'),
        _data_dims=['A', 'B'],
        _extended_coords_data=[]),
    _len=1)

In [558]:
space.ones().array.data

array([[1., 1., 1.],
       [1., 1., 1.]])

In [559]:
ScaleOperator(space.ones().array.data, space=space)

ScaleOperator(
    <xarray.DataArray (A: 2, B: 3)> Size: 48B
    array([[1., 1., 1.],
           [1., 1., 1.]])
    Coordinates:
      * A        (A) int64 16B 1 2
      * B        (B) <U1 12B 'a' 'b' 'c',
    space=XarrayVectorSpace(coords_data=[('A', [1, 2], {}), ('B', ['a', 'b', 'c'], {})], name='foo'))

In [560]:
#| hide
# from pylgs.pymor.example_problems import *

# A, B, C, E = lti_matrices()

# input_space = XarrayVectorSpace({'inputs': ['uniform heating', 'left end heating']}, name='input')

# U = input_space.from_numpy(np.array([.3, .7]))

# U

# matrix=DataArray(B, {'grid': np.linspace(0, 1, 101), 'inputs': U.array.coords['inputs']})

# op = XarrayMatrixOperator(matrix)

# op

# op.apply(U)

# op.range

# op.source

# op.H.source

# op.as_range_array()

# op.as_source_array()

# V=op.range.from_numpy(np.linspace(0, 2, 101))

# op.apply_adjoint(V)

## LincombOperator

In [561]:
a = XarrayMatrixOperator(np.ones([2, 2]), source='source a', range='range a')
b = XarrayMatrixOperator(np.eye(2), source='source a', range='range a')

In [562]:
LincombOperator([a, b], [1., 1.])

LincombOperator(
    (XarrayMatrixOperator(
         <xarray.DataArray (range a (range): 2, source a (source): 2)> Size: 32B
         array([[1., 1.],
                [1., 1.]])
         Coordinates:
           * range a (range)    (range a (range)) int64 16B 0 1
           * source a (source)  (source a (source)) int64 16B 0 1,
         source=XarrayVectorSpace(coords_data=[('source a', array([0, 1]), {})]),
         range=XarrayVectorSpace(coords_data=[('range a', array([0, 1]), {})])),
     XarrayMatrixOperator(
         <xarray.DataArray (range a (range): 2, source a (source): 2)> Size: 32B
         array([[1., 0.],
                [0., 1.]])
         Coordinates:
           * range a (range)    (range a (range)) int64 16B 0 1
           * source a (source)  (source a (source)) int64 16B 0 1,
         source=XarrayVectorSpace(coords_data=[('source a', array([0, 1]), {})]),
         range=XarrayVectorSpace(coords_data=[('range a', array([0, 1]), {})]))),
    (1.0, 1.0))

### _numpy_zero_operator -


In [563]:
#| export
def _numpy_zero_operator(shape):
    return ZeroOperator(*[NumpyVectorSpace(dim) for dim in shape])

### read_sparse_dataarray -


In [564]:
#| export
def _read_sparse_dataarray(
    file_name:str|Path, # File name
)->DataArray:
    if not Path(file_name).suffix: file_name = Path(file_name).with_suffix('.mtxn')
    header = []
    with open(file_name, "r") as reader:
        while True:
            line = next(reader)
            if line[0] != "%": break
            header.append(line.strip('%\n '))
    matrix = pd.read_csv(
        file_name,
        sep=r'\s+',
        header=None,
        skiprows=len(header),
        index_col=None,
        engine="c",
        comment='%'
    )
    name = header[0]
    parameters = header[1].split('\t')
    shape = [int(s) for s in header[2].split()]
    coords = {dim: index.split('\t') for dim, index in zip(header[3::2], header[4::2])}
    matrix = sparse([matrix.iloc[:, :-1].T, matrix.iloc[:, -1]], shape=shape)
    return DataArray(matrix, coords, name=name, attrs={'parameters': parameters})

In [565]:
_read_sparse_dataarray('test')

Format,coo
Data Type,float64
Shape,"(2, 3, 4)"
nnz,2
Density,0.08333333333333333
Read-only,True
Size,64
Storage ratio,0.33


In [566]:
with importlib.resources.path("pylgs.systems.NaD1_Toy", "Flux.mtxn") as path:
    out = _read_sparse_dataarray(path)
out

Format,coo
Data Type,float64
Shape,"(1, 1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,32
Storage ratio,1.00


### from_file -


In [567]:
#| export 
@patch(cls_method=True)
@delegates(LincombOperator.__init__)
def from_file(
    cls:LincombOperator, 
    file_name:str|Path, # File name
    **kwargs # Additional arguments are passed to `LincombOperator`.
):
    """Read a `LincombOperator` (list of sparse arrays and corresponding `ExpressionParameterFunctionals`) from a .mtxn file."""
    da = _read_sparse_dataarray(file_name)
    coefficients = [
        ExpressionParameterFunctional(s, {p: 1 for p in da.parameters if p in s}) if da.parameters != [''] else 1
        for s in da.coords[da.dims[0]].data
    ]
    del da.attrs['parameters']
    # return da
    operators = [XarrayMatrixOperator(d.drop_vars(da.dims[0])) for d in da]    
    return LincombOperator(operators, coefficients, **kwargs)

In [568]:
with importlib.resources.path("pylgs.systems.NaD1_Toy", "b.mtxn") as path:
    op = LincombOperator.from_file(path)
op

Format,coo
Data Type,float64
Shape,"(4, 1)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [569]:
op.as_range_array(Mu({'BeamTransitRatePerS': 1}))

XarrayVectorArray(
    XarrayVectorSpace(
        coords_data=[('Density matrix', array(['ρ<sub>Re, 3S<sub>1/2</sub>, 3S<sub>1/2</sub></sub>',
                            'ρ<sub>Re, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                            'ρ<sub>Im, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                            'ρ<sub>Re, 3P<sub>1/2</sub>, 3P<sub>1/2</sub></sub>'], dtype='<U50'), {})]),
    XarrayVectorArrayImpl(
        array([1., 0., 0., 0.]),
        XarrayVectorSpace(
            coords_data=[('Density matrix', array(['ρ<sub>Re, 3S<sub>1/2</sub>, 3S<sub>1/2</sub></sub>',
                                'ρ<sub>Re, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                                'ρ<sub>Im, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                                'ρ<sub>Re, 3P<sub>1/2</sub>, 3P<sub>1/2</sub></sub>'], dtype='<U50'), {})]),
        _data_dims=['Density matrix'],
        _extended_coords_data=[]),
    _len=1)

In [570]:
with importlib.resources.path("pylgs.systems.NaD1_Toy", "Flux.mtxn") as path:
    op = LincombOperator.from_file(path)
op

Format,coo
Data Type,float64
Shape,"(1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [571]:
op.source

XarrayVectorSpace(
    coords_data=[('Density matrix', array(['ρ<sub>Re, 3S<sub>1/2</sub>, 3S<sub>1/2</sub></sub>',
                        'ρ<sub>Re, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                        'ρ<sub>Im, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                        'ρ<sub>Re, 3P<sub>1/2</sub>, 3P<sub>1/2</sub></sub>'], dtype='<U50'), {})])

In [572]:
op.range

XarrayVectorSpace(coords_data=[])

In [573]:
op.assemble()

Format,coo
Data Type,float64
Shape,"(1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [574]:
# op = LincombOperator.from_file('test.mtxn')
# op

### partial_evaluate -


In [575]:
#| export 
@patch
def partial_evaluate(
    self:ExpressionParameterFunctional, 
    mu:dict|Mu # Parameter values 
)->float|ExpressionParameterFunctional:
    """Substitute parameter values, returning a new `ExpressionParameterFunctional` if expression does not evaluate to a number."""
    mu = {k: v[0] for k, v in mu.items()}
    expr = sy.sympify(self.expression).subs(mu)
    unevaluated = [str(s) for s in expr.free_symbols]
    if expr.is_number:
        return float(expr)
    return ExpressionParameterFunctional(
        str(expr), 
        {k: v for k, v in self.parameters.items() if k in unevaluated}
    )

In [576]:
# op.coefficients[1].partial_evaluate({'A': [.5]})

In [577]:
# op.coefficients[1].partial_evaluate({'A': [.5], 'B': [2.]})

### partial_evaluate_coefficients -


In [578]:
#| export 
@patch
def partial_evaluate_coefficients(
    self:LincombOperator, 
    mu:Mu # Parameter values to substitute
):
    """Substitute parameter values into linear coefficients, returning a new `ExpressionParameterFunctional` if expression does not evaluate to a number."""
    result = []
    for c in self.coefficients:
        try:
            result.append(c.evaluate(mu))
        except AttributeError:
            result.append(c)
        except AssertionError:
            try:
                result.append(c.partial_evaluate(mu))
            except Exception as e:
                result.append(c)
    return result

In [579]:
# op.partial_evaluate_coefficients(Mu({'A': .5}))

### partial_assemble -


In [580]:
#| export 
@patch
def partial_assemble(
    self:LincombOperator, 
    mu=None # Parameter values to substitute
)->Operator:
    """Substitute parameter values into the linear coefficients, returning a new operator with fewer (or no) parameters."""
    operators = tuple(op.assemble(mu) for op in self.operators)
    coefficients = self.partial_evaluate_coefficients(mu)
    evaluated = [[], []]
    unevaluated = [[], []]
    for o, c in zip(operators, coefficients):
        if isinstance(c, Number):
            if c:
                evaluated[0].append(o)
                evaluated[1].append(c)
        else:
            unevaluated[0].append(o)
            unevaluated[1].append(c)
    op = []
    if len(evaluated[0]):
        op.append(assemble_lincomb(
            *evaluated, 
            solver_options=self.solver_options,
            name=self.name + '_partially_assembled'
        ))
    if len(unevaluated[0]):
        op.append(LincombOperator(*unevaluated))
    if len(op) == 0:
        op = [ZeroOperator(range=self.range, source=self.source)]
    op = np.sum(op)
    # To avoid infinite recursions, only use the result if at least one of the following
    # is true:
    #   - The operator is parametric, so the the result of assemble *must* be a different,
    #     non-parametric operator.
    #   - One of self.operators changed by calling 'assemble' on it.
    #   - The result of assemble_lincomb is of a different type than the original operator.
    #   - assemble_lincomb could simplify the list of assembled operators,
    #     which we define to be the case when the number of operators has ben reduced.
    if (self.parametric
            or operators != self.operators  # for this comparison to work self.operators always has to be a tuple!
            or type(op) != type(self)
            or len(op.operators) < len(operators)):
        return op
    else:
        return self

In [581]:
op

Format,coo
Data Type,float64
Shape,"(1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [582]:
# op.partial_assemble(Mu({'A': .5}))

In [583]:
# op.partial_assemble(Mu({'A': .5, 'B': 2.}))

In [584]:
# op.partial_assemble(Mu({'A': 0}))

### terms -


In [585]:
#| export
@patch(as_prop=True)
def terms(self:LincombOperator):
    return [c * o for c, o in zip(self.coefficients, self.operators)]

In [586]:
# #| export
# @patch
# def scalar_part(self:LincombOperator, mu):
#     mu_vector = Mu({k: v for k, v in mu.items() if v.size > 1})
#     return np.sum([o for o in self.terms if not set(mu_vector).intersection(o.parameters)])

In [587]:
# #| export
# @patch
# def vector_part(self:LincombOperator, mu):
#     mu_vector = Mu({k: v for k, v in mu.items() if v.size > 1})
#     return np.sum([o for o in self.terms if set(mu_vector).intersection(o.parameters)])

## ProductOperator

In [588]:
#| export 
class ProductOperator(Operator):
    """An Operator given by the direct product of operators `operators`."""
    
    suboperator_symbol = '⛒'
    
    def __init__(
        self, 
        operators, # Sequence of operators that each assemble to XarrayMatrixOperator
        name=None, # Optional name
    ):
        for op in operators:
            if not isinstance(op, Operator): raise ValueError(f'Input {op} should be an Operator.')
        self.source = np.prod([op.source for op in operators])
        self.range = np.prod([op.range for op in operators])
        self.__auto_init(locals())
        self.linear = True
        
    def apply(self, U, mu=None):
        pass

    

In [589]:
A = XarrayMatrixOperator(array([[1, 0], [0, 1]]), source=['source a'], range=['range a'])
B = XarrayMatrixOperator(array([[0, 1], [1, 0]]), source=['source b'], range=['range b'])

In [590]:
#| export
@patch
def __mul__(self:Operator, other):
    if isinstance(other, Operator) and all(isinstance(space, XarrayVectorSpace) for space in [self.source, self.range, other.source, other.range]):
        return ProductOperator([self, other])
    assert isinstance(other, (Number, ParameterFunctional))
    # from pymor.operators.constructions import LincombOperator
    if self.name != 'LincombOperator' or not isinstance(self, LincombOperator):
        return LincombOperator((self,), (other,))
    else:
        return self.with_(coefficients=tuple(c * other for c in self.coefficients))

In [591]:
#| export
@patch
def __str__(self:ProductOperator):
    return ' ⨂ '.join(str(o) for o in self.operators)

In [592]:
#| export
@patch
def __str__(self:IdentityOperator):
    return f'I{_mapping_str(self)}'

In [593]:
A * IdentityOperator(B.source)

ProductOperator(
    [XarrayMatrixOperator(
         <xarray.DataArray (range a (range): 2, source a (source): 2)> Size: 32B
         array([[1, 0],
                [0, 1]])
         Coordinates:
           * range a (range)    (range a (range)) int64 16B 0 1
           * source a (source)  (source a (source)) int64 16B 0 1,
         source=XarrayVectorSpace(coords_data=[('source a', array([0, 1]), {})]),
         range=XarrayVectorSpace(coords_data=[('range a', array([0, 1]), {})])),
     IdentityOperator(XarrayVectorSpace(coords_data=[('source b', array([0, 1]), {})]))])

In [594]:
IdentityOperator(B.source) * A

ProductOperator(
    [IdentityOperator(XarrayVectorSpace(coords_data=[('source b', array([0, 1]), {})])),
     XarrayMatrixOperator(
         <xarray.DataArray (range a (range): 2, source a (source): 2)> Size: 32B
         array([[1, 0],
                [0, 1]])
         Coordinates:
           * range a (range)    (range a (range)) int64 16B 0 1
           * source a (source)  (source a (source)) int64 16B 0 1,
         source=XarrayVectorSpace(coords_data=[('source a', array([0, 1]), {})]),
         range=XarrayVectorSpace(coords_data=[('range a', array([0, 1]), {})]))])

In [595]:
def vec(a):
    return a.T.ravel()

In [596]:
s=1

In [597]:
A = XarrayMatrixOperator(
    sparse2d_rand([3*s, 2*s], density=.1, random_state=42), 
    source='source a',
    range='range a'
)
A

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33


In [598]:
mu = Mu(A=.5)

In [599]:
B = ExpressionParameterFunctional('A**2', {'A': 1}) * XarrayMatrixOperator(
    sparse2d_rand([4*s, 5*s], density=.1, random_state=42),
    source='source b',
    range='range b'
)
B = B.assemble(mu)

In [600]:
op = A * B
op

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33
Format,coo
Data Type,float64
Shape,"(4, 5)"


In [601]:
op.source

XarrayVectorSpace(coords_data=[('source a', array([0, 1]), {}), ('source b', array([0, 1, 2, 3, 4]), {})])

In [602]:
op.range

XarrayVectorSpace(coords_data=[('range a', array([0, 1, 2]), {}), ('range b', array([0, 1, 2, 3]), {})])

In [603]:
B.source._array

<xarray.DataArray 'XarrayVectorSpace' (source b: 5)> Size: 40B
array([0., 0., 0., 0., 0.])
Coordinates:
  * source b  (source b) int64 40B 0 1 2 3 4

In [604]:
sum_op = SumOperator(B.source._array['source b'])

In [605]:
sum_op * A

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33


In [606]:
A * sum_op

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33


In [607]:
np.random.seed(42)
U = op.source.from_numpy(np.random.rand(op.source._array.size))
V = op.range.from_numpy(np.random.rand(op.range._array.size))

In [608]:
U.space

XarrayVectorSpace(coords_data=[('source a', array([0, 1]), {}), ('source b', array([0, 1, 2, 3, 4]), {})])

In [609]:
An = A.matrix.data
Bn = B.assemble(mu).matrix.data
Un = U.to_numpy().T
Vn = V.to_numpy().T

In [610]:
%%time 
An = A.matrix.data
Bn = B.assemble(mu).matrix.data
Un = U.to_numpy().T
out1 = np.kron(An, Bn).dot(vec(Un))

CPU times: user 639 μs, sys: 103 μs, total: 742 μs
Wall time: 662 μs


In [611]:
%%time
An = A.matrix.data
Bn = B.assemble(mu).matrix.data
Un = U.array.T.data
out3 = An.dot(Bn.dot(Un).T).ravel()

CPU times: user 606 μs, sys: 321 μs, total: 927 μs
Wall time: 642 μs


In [612]:
%%time
out4 = A.apply(B.apply(U)).to_numpy()

CPU times: user 2.72 ms, sys: 83 μs, total: 2.8 ms
Wall time: 2.75 ms


In [613]:
test_close(out1.ravel(), out3.ravel())
test_close(out1.ravel(), out4.ravel())

In [614]:
test_close(
    np.kron(An, Bn).dot(vec(Un)),
    An.dot(Bn.dot(Un).T).ravel()
)

 N.B.: `to_numpy` on a `NumpyVectorArray` effectively takes the transpose.

### apply -


In [615]:
#| export 
@patch
def apply(self:ProductOperator, U, mu=None):
    U = U.copy()
    for op in self.operators[::-1]:
        U = op.assemble(mu).apply(U)
    return self.range.from_xarray(U.array)

In [616]:
W = space.from_numpy(np.arange(12), extended_coords_data='len')

In [617]:
C = ScaleOperator(W.array[0, 0].drop_vars(['A', 'len']), name='C')
C.apply(W).name

'C'

In [618]:
#| hide
test_eq(_, 'C')

In [619]:
D = SumOperator(W.array.A, name='D')
D.apply(W).name

'D'

In [620]:
#| hide
test_eq(_, 'D')

In [621]:
C = ScaleOperator(W.array[0, 0].drop_vars(['A', 'len']))
E = (C * D)
E.apply(W).name

'XarrayVectorArray'

In [622]:
E.name

'ProductOperator'

In [623]:
#| hide
# test_eq(_, 'D')

In [624]:
E = C * (C * D)
E.apply(W).array.name

In [625]:
#| hide
# test_eq(_, 'D')

In [626]:
%%time 
K = A * B.assemble(mu)
out2 = K.apply(U).to_numpy()

CPU times: user 3.33 ms, sys: 69 μs, total: 3.4 ms
Wall time: 3.37 ms


In [627]:
# test_close(out1.ravel(), out2.ravel())

In [628]:
test_close(
    op.apply(U, mu).to_numpy().ravel(), 
    np.kron(An, Bn).dot(vec(Un))
)

$(A\bigotimes B)^T=A^T\bigotimes B^T$

In [629]:
test_close(np.kron(An, Bn).T, np.kron(An.T, Bn.T))

### H -


In [630]:
#| export 
@patch(as_prop=True)
def H(self:ProductOperator):
    return self.with_(operators=[op.H for op in self.operators])

In [631]:
op.H

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33
Format,coo
Data Type,float64
Shape,"(4, 5)"


$\text{vec}(V)(A\bigotimes B)=(A\bigotimes B)^T\text{vec}(V)$.

In [632]:
op.H.source

XarrayVectorSpace(coords_data=[('range a', array([0, 1, 2]), {}), ('range b', array([0, 1, 2, 3]), {})])

In [633]:
test_close(
    vec(Vn).dot(np.kron(An, Bn).todense()),
    (np.kron(An, Bn).T).dot(vec(Vn))
)

### apply_adjoint -


In [634]:
#| export 
@patch
def apply_adjoint(self:ProductOperator, V, mu=None):
    return self.H.apply(V, mu=mu)

In [635]:
test_close(
    op.apply_adjoint(V, mu).to_numpy().ravel(),
    vec(Vn).dot(np.kron(An, Bn).todense())
)

### assemble -


In [636]:
#| export 
@patch
def assemble(self:ProductOperator, mu=None):
    operators = [op.assemble(mu) for op in self.operators]
    if any(isinstance(op, ZeroOperator) for op in operators): return ZeroOperator(self.range, self.source)
    if all(op == old_op for op, old_op in zip(operators, self.operators)): return self 
    return self.with_(operators=operators)

In [637]:
op.assemble(mu)

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33
Format,coo
Data Type,float64
Shape,"(4, 5)"


In [638]:
zero = (0 * B).assemble()

In [639]:
(A * zero).assemble()

ZeroOperator(
    XarrayVectorSpace(coords_data=[('range a', array([0, 1, 2]), {}), ('range b', array([0, 1, 2, 3]), {})]),
    XarrayVectorSpace(coords_data=[('source a', array([0, 1]), {}), ('source b', array([0, 1, 2, 3, 4]), {})]))

### expand_ProductOperator -


In [640]:
#| exporti
@match_class(ProductOperator)
def expand_ProductOperator(self, op):
    op = self.replace_children(op)

    # merge child ProductOperators
    if any(isinstance(o, ProductOperator) for o in op.operators):
        ops = []
        for o in op.operators:
            if isinstance(o, ProductOperator):
                ops.extend(o.operators)
            else:
                ops.append(o)
        op = op.with_(operators=ops)

    # expand products with LincombOperators
    if any(isinstance(o, LincombOperator) for o in op.operators):
        i = next(iter(i for i, o in enumerate(op.operators) if isinstance(o, LincombOperator)))
        left, right = op.operators[:i], op.operators[i+1:]
        ops = [ProductOperator(left + (o,) + right) for o in op.operators[i].operators]
        op = op.operators[i].with_(operators=ops)

        # there can still be LincombOperators within the summands so we recurse ..
        op = self.apply(op)
    return op

#| export
ExpandRules.insert_rule(-1, expand_ProductOperator)

### contract_ProductOperator -


In [641]:
#| exporti
@match_class(ProductOperator)
def contract_ProductOperator(self, op):
    op = self.replace_children(op)
    if any(isinstance(o, ZeroOperator) for o in op.operators): return ZeroOperator(op.range, op.source)
    xarray_operators = [o for o in op.operators if     isinstance(o, XarrayMatrixOperator)]
    other_operators  = [o for o in op.operators if not isinstance(o, XarrayMatrixOperator)]
    if xarray_operators:
        matrices, ranges, sources = unzip([(o.matrix, o.range, o.source) for o in xarray_operators])
        op = XarrayMatrixOperator(
            math.prod(matrices), 
            source=math.prod(sources, start=XarrayVectorSpace()), 
            range=math.prod(ranges, start=XarrayVectorSpace())
        )
    else:
        op = 1
    if other_operators:
        op *= math.prod(other_operators) 
    return op

ContractRules.insert_rule(-2, contract_ProductOperator)

In [642]:
#| hide
contract(op)

Format,coo
Data Type,float64
Shape,"(3, 2, 4, 5)"
nnz,2
Density,0.016666666666666666
Read-only,True
Size,80
Storage ratio,0.08


### to_matrix -

In [643]:
# #| hide
# #| exporti
# @match_class(ProductOperator)
# def to_matrix_ProductOperator(self, op):
#     return self.apply(contract(op))
    
# ToMatrixRules.insert_rule(-2, to_matrix_ProductOperator)

In [644]:
# #| hide
# to_matrix(op, mu=mu)

In [645]:
#| hide
#| exporti
@match_class(ProductOperator)
def to_matrix_ProductOperator(self, op):
    return kron(*[self.apply(o) for o in op.operators])
    
ToMatrixRules.insert_rule(-2, to_matrix_ProductOperator)

In [646]:
to_matrix(op, mu=mu)

<Compressed Sparse Row sparse array of dtype 'float64'
	with 2 stored elements and shape (12, 10)>

In [647]:
test_array('operators', 'to_matrix_ProductOperator_1', _.todense())

### as_source_array -


In [648]:
self = op

In [649]:
contract(self.assemble(mu)).matrix

Format,coo
Data Type,float64
Shape,"(3, 2, 4, 5)"
nnz,2
Density,0.016666666666666666
Read-only,True
Size,80
Storage ratio,0.08


In [650]:
#| export 
@patch
def as_source_array(self:ProductOperator, mu=None):
    return contract(self.assemble(mu)).as_source_array()

In [651]:
# op.as_source_array(mu)

In [652]:
# test_close(
#     np.kron(An, Bn).todense().ravel(),
#     op.as_source_array(mu).to_numpy().T.ravel()
# )

### as_range_array -


In [653]:
#| export 
@patch
def as_range_array(self:ProductOperator, mu=None):
    return contract(self.assemble(mu)).as_range_array()

In [654]:
# test_close(
#     np.kron(An, Bn).todense().ravel(),
#     op.as_range_array(mu).to_numpy().ravel()
# )

## Export -

In [655]:
#| hide
import nbdev; nbdev.nbdev_export()