In [ ]:
#| default_exp pymor.operators

# pymor.operators

> Extended functionality for [pyMOR](https://pymor.org/) operators

## Imports

In [ ]:
# | hide
from fastcore.test import test_eq, test_close
from pylgs.utilities.testing import test_array

In [ ]:
#| export
from __future__ import annotations
from pathlib import Path
import importlib
from numbers import Number
import math
from functools import reduce

from fastcore.basics import patch
from fastcore.meta import delegates
from pydash import unzip

import numpy as np
from numpy import array, ndarray
from scipy.sparse import issparse, sparray
from sparse import SparseArray
import sympy as sy
import pandas as pd
from xarray import DataArray, Coordinates

from pymor.basic import LincombOperator, NumpyMatrixOperator, ZeroOperator, ExpressionParameterFunctional, NumpyVectorSpace, Mu, IdentityOperator, Parameters
from pymor.models.interface import Model
from pymor.algorithms.to_matrix import to_matrix, ToMatrixRules
from pymor.algorithms.simplify import ExpandRules, expand, ContractRules, contract
from pymor.algorithms.rules import match_class, RuleTable
from pymor.algorithms.lincomb import assemble_lincomb
from pymor.operators.interface import Operator
from pymor.core.base import abstractmethod
from pymor.parameters.functionals import ParameterFunctional

from pylgs.utilities.xarray import *
from pylgs.utilities.sparse import sparse, sparse2d, kron, sparse2d_rand
from pylgs.pymor.parameters import *
from pylgs.pymor.vectorarrays import *

In [ ]:
import xarray as xr

In [ ]:
from IPython.display import HTML

In [ ]:
# HTML('''<style>
# html,body,address,blockquote,div,form,fieldset,caption,h1,h2,h3,h4,h5,h6,hr,ul,ol,ul,li,table,tr,td,th,p,img {margin:0; padding:0;}
# ul, ol, li {list-style-type: none;}
# img,fieldset{border: none;}
# ul {margin-left: -2em}
# </style>''')

In [ ]:
# HTML('''foo<ul><li>foo</li></ul>foo''')

In [ ]:
#|export
LincombOperator.suboperator_symbol = '+'

In [ ]:
#|export
def _mapping_str(op:Operator):
    try:
        return f"{op.source._repr_html_(show_details=False)} → {op.range._repr_html_(show_details=False)}"
    except AttributeError:
        return f"{str(op.source)} → {str(op.range)}"

In [ ]:
#|export
def _operator_group_tag(
    level:int, 
    cls:str, 
    mapping:str, 
    name:str|None=None,
    parameters:str|None=None,
    contents:str|None=None,
    suboperators:list(str)|None=None, 
    symbol:str|None=None, 
    opened:bool=False
) -> str:
    if suboperators or contents:
        return f'''
            <li>
                <details {'open' if opened else 'closed'}>
                    <summary>
                        <ul class="operator">
                            {'<li>' + name + '</li>' if name else ''}
                            <li>{cls}</li>
                            <li>{mapping}</li>
                            {'<li>' + parameters + '</li>' if parameters else ''}
                        </ul>
                    </summary>
                    <ul class="operator-group operator-group-{'even' if not (level % 2) else 'odd'}">
                        {contents or symbol.join(suboperators)}
                    </ul>
                </details>
            </li>
        '''
    else:
        return f'''
            <li>
                <ul class="operator">
                    {'<li>' + name + '</li>' if name else ''}
                    <li>{cls}</li>
                    <li>{mapping}</li>
                    {'<li>' + parameters + '</li>' if parameters else ''}
                </ul>
            </li>
        '''

In [ ]:
#|export
def _operator_html_node(op:Operator, level:int=0, opened:bool=False) -> str:
    cls = op.__class__.__name__
    name = op.name if op.name != cls else None
    mapping = _mapping_str(op)
    parameters = str(list(Parameters.of(op)))
    contents = None
    if hasattr(op, 'operators'):
        suboperators = [_operator_html_node(o, level=level + 1, opened=opened) for o in op.operators]
        symbol = op.suboperator_symbol
        return _operator_group_tag(level, cls, mapping, name, parameters, contents, suboperators, symbol, opened)
    if hasattr(op, 'matrix'):
        contents = op.matrix._repr_html_() if hasattr(op.matrix, '_repr_html_') else str(op.matrix)
        return _operator_group_tag(level, cls, mapping, name, parameters, contents)
    return _operator_group_tag(level, cls, mapping, name, parameters)

In [ ]:
#|export
def operator_html_tree(op:Operator, opened:bool=False) -> str:
    style = """
    <style>
        .operator-group summary {
            list-style: none;
            display: flex;
            gap: 0.25em;
            align-items: start;
            cursor: pointer;
        }
        .operator-group summary::before {
            content: '▶︎';
            font-size: 75%;
            align-items: center;
            width: 1em;
            flex-shrink: 0;
            transition: 0.3s;
        }
        .operator-group details[open] > summary::before {
            transform: rotate(90deg);
            transform-origin: 40% 45% 0;
        }
        .operator-group-odd > li {
            background-color: #f0f0f0;;
        }
        .operator-group-even > li {
            background-color: #fbfbfb;
        }
        .operator-group {
            display: flex;
            gap: .4em;
            align-items: center;
            padding: 0px;
            margin-left: -2em;
            margin-top: .25em;
        }
        .operator-group > li {
            list-style-type: none;
            border: 1px solid black;
            border-radius: .25em;
            padding: .25em;
        }
        .operator {
            margin: 0;
            padding: 0;
            margin-top: -.2em;
            margin-left: -2em;
        }
        .operator > li {
            list-style-type: none;
            border: none;
            padding: 0;
            line-height: 1.25em;
        }
    </style>
    """
    return style + f'<ul class="operator-group operator-group-odd">{_operator_html_node(op, opened=opened)}</ul>'

In [ ]:
op = LincombOperator(
    [
        NumpyMatrixOperator(np.ones([1])), 
        LincombOperator([NumpyMatrixOperator(np.ones([1]))] * 2, [.1] * 2)
    ],
    [1.] * 2
)
HTML(operator_html_tree(op, True))

In [ ]:
#|export
@patch
def _repr_html_(self:Operator):
    return operator_html_tree(self)

In [ ]:
NumpyMatrixOperator(np.ones([1]))

NumpyMatrixOperator(<1x1 dense>, solver=ScipyLUSolveSolver(check_finite=True))

In [ ]:
op

LincombOperator(
    (NumpyMatrixOperator(<1x1 dense>, solver=ScipyLUSolveSolver(check_finite=True)),
     LincombOperator(
         (NumpyMatrixOperator(<1x1 dense>, solver=ScipyLUSolveSolver(check_finite=True)),
          NumpyMatrixOperator(<1x1 dense>, solver=ScipyLUSolveSolver(check_finite=True))),
         (0.1, 0.1))),
    (1.0, 1.0))

## XarrayMatrixOperator

In [ ]:
#| exporti
class XarrayMatrixBasedOperator(Operator):
    """Base class for operators that assemble into an `XarrayMatrixOperator`."""

    linear = True

    @property
    def H(self):
        if not self.parametric:
            return self.assemble().H
        else:
            return super().H

    @abstractmethod
    def assemble(self, mu=None): pass

    def apply(self, U, mu=None):
        return self.range.from_xarray(self.assemble(mu).matrix.dot(U.impl._array))

    def apply_adjoint(self, V, mu=None):
        return self.assemble(mu).apply_adjoint(V)

    def as_range_array(self, mu=None):
        matrix = unlabel_dims(self.assemble(mu).matrix.squeeze())
        extended_coords = {d: matrix.coords[d] for d in matrix.dims if d not in self.range.dims}
        return self.range.from_numpy(self.matrix.data, extended_coords)

    def as_source_array(self, mu=None):
        matrix = unlabel_dims(self.assemble(mu).matrix.squeeze())
        extended_coords = {d: matrix.coords[d] for d in matrix.dims if d not in self.source.dims}
        return self.source.from_numpy(self.matrix.data, extended_coords).conj()

    @property
    def display_name(self):
        return self.name if self.name != self.__class__.__name__ else 'X'

    def __str__(self):
        return f"{self.display_name}{_mapping_str(self)}"

### _ndims -


In [ ]:
#| export
def _ndims(matrix):
    if isinstance(matrix, DataArray):
        return len(matrix.dims)
    else:
        return matrix.ndim    

### _get_space_dims -


In [ ]:
# #| export
# def _get_space_dims(dims, matrix, default):
#     if dims is None:
#         if hasattr(matrix, 'dims'): return list(matrix.dims)
#         else: return [default]
#     elif isinstance(dims, str): return [dims]
#     elif hasattr(dims, 'dims'): return dims.dims
#     return list(dims)

### XarrayMatrixOperator -

In [ ]:
#|export
def _label_dims_with(obj, lbl):
    if isinstance(obj, XarrayVectorSpace):
        return obj.with_(coord_data = _label_dims_with(obj.coord_data, lbl))
    if isinstance(obj, list | tuple): 
        return [d + lbl for d in obj]
    if isinstance(obj, dict):
        return {k + lbl: v for k,v in obj.items()}

In [ ]:
space_a = XarrayVectorSpace({'A': np.linspace(0, 1, 2)})

In [ ]:
_label_dims_with(['A'], Lbl.SRC)

['A (source)']

In [ ]:
_label_dims_with(validate_coord_data(space_a.coords), Lbl.SRC)

{'A (source)': (array([0., 1.]), {})}

In [ ]:
_label_dims_with(space_a, Lbl.SRC)

XarrayVectorSpace(coord_data={A (source): (array([0., 1.]),)})

In [ ]:
#|export
def _label_dims(obj, src_dims, rng_dims):
    if isinstance(obj, XarrayVectorSpace):
        coord_data = {_label_dims(k, src_dims, rng_dims): v for k,v in obj.coord_data.items()}
        return obj.with_(coord_data=coord_data)
    if isinstance(src_dims, str): src_dims = [src_dims]
    if isinstance(rng_dims, str): rng_dims = [rng_dims]
    labled_src_dims = _label_dims_with(src_dims, Lbl.SRC)
    labled_rng_dims = _label_dims_with(rng_dims, Lbl.RNG)
    rename_dict = dict(zip(src_dims, labled_src_dims)) | dict(zip(rng_dims, labled_rng_dims))
    match obj:
        case str():
            return rename_dict.get(obj, obj)
        case list() | tuple():
            return [rename_dict.get(dim, dim) for dim in obj]
        case DataArray():
            return obj.rename(rename_dict)
        case Coordinates():
            return Coordinates({rename_dict.get(k, k): v.data for k,v in obj.items()})

In [ ]:
matrix = DataArray(
        np.arange(6).reshape(2, 3), 
        {'A': np.linspace(0, 1, 2), 'B': np.linspace(0, 1, 3)}
    )

In [ ]:
matrix = _label_dims(matrix, ['A'], ['B'])
matrix

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [ ]:
crds = _label_dims(space_a.coords, ['A'], ['B'])
crds

Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0

In [ ]:
spc = _label_dims(space_a, ['A'], ['B'])
spc

XarrayVectorSpace(coord_data={A (source): (array([0., 1.]),)})

In [ ]:
matrix

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [ ]:
unlabel_dims('A (source)')

'A'

In [ ]:
unlabel_dims(matrix)

<xarray.DataArray (A: 2, B: 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A        (A) float64 16B 0.0 1.0
  * B        (B) float64 24B 0.0 0.5 1.0

In [ ]:
unlabel_dims(crds)

Coordinates:
  * A        (A) float64 16B 0.0 1.0

In [ ]:
spc

XarrayVectorSpace(coord_data={A (source): (array([0., 1.]),)})

In [ ]:
unlabel_dims(spc)

XarrayVectorSpace(coord_data={A: (array([0., 1.]),)})

In [ ]:
#|export
def _swap_dim_labels(da):
    src_dims = [d for d in da.dims if d.endswith(Lbl.SRC)]
    rng_dims = [d for d in da.dims if d.endswith(Lbl.RNG)]
    rename_dict = {d: d.replace(Lbl.SRC, Lbl.RNG) for d in src_dims} | {d: d.replace(Lbl.RNG, Lbl.SRC) for d in rng_dims}
    return da.rename(rename_dict)

In [ ]:
_swap_dim_labels(matrix)

<xarray.DataArray (A (range): 2, B (source): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (range)   (A (range)) float64 16B 0.0 1.0
  * B (source)  (B (source)) float64 24B 0.0 0.5 1.0

In [ ]:
#|export
def _is_labeled_da(da):
    if not isinstance(da, DataArray): return False
    return any(d.endswith(Lbl.SRC) or d.endswith(Lbl.RNG) for d in da.dims)

In [ ]:
#|export
def coordinates_to_list(coords, dims):
    return [(d, coords[d].data, coords[d].attrs) for d in dims]

In [ ]:
#| export
def _get_space_dims(dims):
    if dims is None: return None, None
    if isinstance(dims, dict): dims = Coordinates(dims)
    if isinstance(dims, Coordinates): return list(dims), dims
    if isinstance(dims, str): dims = [dims]
    if isinstance(dims, list | tuple): return dims, None
    if hasattr(dims, 'dims'): return dims.dims, dims.coords
    raise ValueError("Source or range specification not valid")

In [ ]:
#| export
class XarrayMatrixOperator(XarrayMatrixBasedOperator):
    """An `Operator` backed by an xarray `DataArray`."""

    def __init__(
        self, 
        matrix:DataArray|ndarray|SparseArray|sparray, # N-dimensional matrix
        source:XarrayVectorSpace|DataArray|Coordinates|dict|list|str|None=None, # Source vector space or coordinates
        range:XarrayVectorSpace|DataArray|Coordinates|dict|list|str|None=None, # Range vector space or coordinates
        solver_options:dict=None, # Options for matrix solver
        name:str=None # Operator name
    ):
        if issparse(matrix): matrix = sparse(matrix)
        if not isinstance(matrix, DataArray):
            if not isinstance(source, XarrayVectorSpace): 
                if isinstance(source, str): source = [source]
                if source is not None: 
                    source = validate_coord_data(source, matrix.shape[-len(source):])
                source = XarrayVectorSpace(source)
            if not isinstance(range, XarrayVectorSpace):
                if isinstance(range, str): range = [range]
                if range is not None:
                    range = validate_coord_data(range, matrix.shape[:len(range)])
                range = XarrayVectorSpace(range)
            labeled_source = _label_dims_with(source, Lbl.SRC)
            labeled_range = _label_dims_with(range, Lbl.RNG)
            matrix = DataArray(
                matrix, 
                dims=labeled_range.dims + labeled_source.dims,
                coords=make_coordinates(labeled_range.coord_data | labeled_source.coord_data),
                name=name
            )
        else:
            if not _is_labeled_da(matrix): matrix = _label_dims(matrix, source, range)
            coords = validate_coord_data(matrix)
            labeled_source = XarrayVectorSpace({k:v for k,v in coords.items() if k.endswith(Lbl.SRC)})
            labeled_range = XarrayVectorSpace({k:v for k,v in coords.items() if k.endswith(Lbl.RNG)})
            source = unlabel_dims(labeled_source)
            range = unlabel_dims(labeled_range)
        if name is None: name = matrix.name
        self.__auto_init(locals())
        self.labeled_source = labeled_source
        self.labeled_range = labeled_range

    def assemble(self, mu=None): return self

    @property
    def size(self):
        return self.matrix.size
        
    @property
    def sparse(self):
        return isinstance(self.matrix.data, SparseArray)

A pyMOR `Operator` maps a `VectorArray` from a source `VectorSpace` to another `VectorArray` in a range `VectorSpace`. The `XarrayMatrixOperator` acts on an `XarrayVectorArray` from an `XarrayVectorSpace` by means of multiplication by an xarray `DataArray`.

The `html` representation of an `XarrayMatrixOperator` is *operator name*{*source space*} → {*range space*}, where X is used as the name if the operator has not been given an explict name.

The matrix can be supplied as a `DataArray`, or as an unlabeled numpy `ndarray`, scipy.sparse `sparray`, or sparse `SparseArray`. 

Create from a numpy array and specified range and source spaces:

In [ ]:
space_a = XarrayVectorSpace({'A': np.linspace(0, 1, 2)})
space_b = XarrayVectorSpace({'B': ['c', 'd', 'e']})
op = XarrayMatrixOperator(np.arange(6).reshape(2, 3), source=space_b, range=space_a, name='foo')
op

XarrayMatrixOperator(
    <xarray.DataArray 'foo' (A (range): 2, B (source): 3)> Size: 48B
    array([[0, 1, 2],
           [3, 4, 5]])
    Coordinates:
      * A (range)   (A (range)) float64 16B 0.0 1.0
      * B (source)  (B (source)) <U1 12B 'c' 'd' 'e',
    source=XarrayVectorSpace(coord_data={B: (['c', 'd', 'e'],)}),
    range=XarrayVectorSpace(coord_data={A: (array([0., 1.]),)}),
    name='foo')

The `DataArray` backing the `Operator` is stored in the `matrix` attribute:

In [ ]:
op.matrix

<xarray.DataArray 'foo' (A (range): 2, B (source): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (range)   (A (range)) float64 16B 0.0 1.0
  * B (source)  (B (source)) <U1 12B 'c' 'd' 'e'

The `source` and `range` attributes store the corresponding `VectorArray`s:

In [ ]:
op.source

XarrayVectorSpace(coord_data={B: (['c', 'd', 'e'],)})

In [ ]:
op.range

XarrayVectorSpace(coord_data={A: (array([0., 1.]),)})

Create from a `DataArray` with defined coords:

In [ ]:
da = DataArray(
        np.arange(6).reshape(2, 3), 
        {'A (source)': np.linspace(0, 1, 2), 'B (range)': np.linspace(0, 1, 3)}
    )

In [ ]:
op = XarrayMatrixOperator(da)
op

XarrayMatrixOperator(
    <xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
    array([[0, 1, 2],
           [3, 4, 5]])
    Coordinates:
      * A (source)  (A (source)) float64 16B 0.0 1.0
      * B (range)   (B (range)) float64 24B 0.0 0.5 1.0,
    source=XarrayVectorSpace(coord_data={A: (array([0., 1.]), {})}),
    range=XarrayVectorSpace(coord_data={B: (array([0. , 0.5, 1. ]), {})}))

In [ ]:
op.matrix

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [ ]:
op.range

XarrayVectorSpace(coord_data={B: (array([0. , 0.5, 1. ]), {})})

In [ ]:
da = DataArray(
        np.arange(6).reshape(2, 3), 
        {'A': np.linspace(0, 1, 2), 'B': np.linspace(0, 1, 3)}
    )

In [ ]:
_label_dims(da, src_dims=['A'], rng_dims=['B'])

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [ ]:
op = XarrayMatrixOperator(da, source=['A'], range=['B'])
op

XarrayMatrixOperator(
    <xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
    array([[0, 1, 2],
           [3, 4, 5]])
    Coordinates:
      * A (source)  (A (source)) float64 16B 0.0 1.0
      * B (range)   (B (range)) float64 24B 0.0 0.5 1.0,
    source=XarrayVectorSpace(coord_data={A: (array([0., 1.]), {})}),
    range=XarrayVectorSpace(coord_data={B: (array([0. , 0.5, 1. ]), {})}))

In [ ]:
op.matrix

<xarray.DataArray (A (source): 2, B (range): 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A (source)  (A (source)) float64 16B 0.0 1.0
  * B (range)   (B (range)) float64 24B 0.0 0.5 1.0

In [ ]:
XarrayMatrixOperator(sparse2d_rand([4, 5], density=.5, random_state=42), source='A', range='B')

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


In [ ]:
op = XarrayMatrixOperator(sparse2d_rand([4, 5], density=.5, random_state=42), source={'A': np.arange(5)}, range={'B': np.arange(4)})
op

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


In [ ]:
op.matrix

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


### H -


In [ ]:
#| export
@patch(as_prop=True)
def H(self:XarrayMatrixOperator):
    """The adjoint operator."""
    adjoint_matrix = self.matrix if np.isrealobj(self.matrix) else self.matrix.conj()           
    options = {'inverse': self.solver_options.get('inverse_adjoint'),
               'inverse_adjoint': self.solver_options.get('inverse')} if self.solver_options else None
    return self.with_(matrix=_swap_dim_labels(adjoint_matrix), solver_options=options, name=self.name + '_adjoint')

In [ ]:
op

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


In [ ]:
op.H

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


### apply -


In [ ]:
#|export
def contract_matvec(a, b, axes):
    """Contract one axis of the first (2D) array with one axis of the second (ND) array."""
    out = np.tensordot(a, b, axes)
    if a.ndim == 1: return out
    return np.moveaxis(out, 0, axes[1])

In [ ]:
contract_matvec(np.ones([2,5]), np.ones([4,5,6]), [1, 1]).shape

(4, 2, 6)

In [ ]:
contract_matvec(np.ones([6,2]), np.ones([4,5,6]), [0, 2]).shape

(4, 5, 2)

In [ ]:
#|export
def dims_matvec(a, b):
    """Contract one axis of the first (2D) array with the axis of the second (ND) array of the same name."""
    a, adims = a
    b, bdims = b
    ax = [[adims.index(d), i] for i,d in enumerate(bdims) if d in adims][0]
    newdims = list(bdims)
    if len(adims) == 1:
        newdims.pop(ax[1])
    else:
        newdims[ax[1]] = adims[1 - ax[0]]
    return contract_matvec(a, b, ax), newdims

In [ ]:
dims_matvec([np.ones([2,5]), ["A", "B"]], [np.ones([4,5,6]), ["C", "B", "D"]])

(array([[[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]],
 
        [[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]],
 
        [[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]],
 
        [[5., 5., 5., 5., 5., 5.],
         [5., 5., 5., 5., 5., 5.]]]),
 ['C', 'A', 'D'])

In [ ]:
dims_matvec([np.ones([2]), ['A']], [np.ones([2, 3]), ['A', 'B']])

(array([2., 2., 2.]), ['B'])

In [ ]:
#| export
@patch
def __truediv__(self:XarrayVectorSpace, other):
    if not isinstance(other, XarrayVectorSpace): raise NotImplementedError
    return self.with_(coords={k: v for k,v in self.coords.items() if k not in other.coords})

In [ ]:
#| export
def replace_item(dct, old_key, new_pair):
    return dict(new_pair if k == old_key else (k, v) for k,v in dct.items())

In [ ]:
#| export
@patch
def range_under(self:XarrayVectorSpace, op:XarrayMatrixOperator):
    """Find the space that this space is mapped to by an XarrayMatrixOperator. Assumes that the operator has one-dimensional source and range."""
    source_dim = op.source.dims[0]
    if not op.range.dims:
        coords = {k:v for k,v in self.coord_data.items() if k != source_dim}
    else:
        range_dim = op.range.dims[0]
        range_coord = op.range.coord_data[range_dim]
        coords = replace_item(self.coord_data, source_dim, (range_dim, range_coord))
    return self.with_(coord_data=coords)

In [ ]:
U = op.source.zeros({'len': [0]})

In [ ]:
U.space.range_under(op)

XarrayVectorSpace(coord_data={B: (array([0, 1, 2, 3]),)})

In [ ]:
S = XarrayVectorSpace({'A': np.arange(3)})

In [ ]:
op1 = XarrayMatrixOperator(np.ones(3), source=S)

In [ ]:
S.range_under(op1)

XarrayVectorSpace(coord_data={})

In [ ]:
S = XarrayVectorSpace({'A': np.arange(3), 'B': np.arange(2)})

In [ ]:
S.range_under(op1)

XarrayVectorSpace(coord_data={B: (array([0, 1]),)})

In [ ]:
#| export
@patch
def apply(
    self:XarrayMatrixOperator, 
    U, # `XarrayVectorArray` of vectors to which the operator is applied
    mu=None, # The parameter values for which to evaluate the operator
    method='numpy',
)->XarrayVectorArray: # `XarrayVectorArray` in the range `XarrayVectorSpace`
    """Apply the operator to an `XarrayVectorArray` in the source vector space."""
    assert U in self.source
    if method == 'numpy':
        src_dims = _label_dims(U.array.dims, U.dims, [])
        out, out_dims = dims_matvec((self.matrix.data, self.matrix.dims), (U.array.data, src_dims))
        out = U.space.range_under(self).from_numpy(out, extended_coord_data=U.extended_coord_data)
    else:
        out = U.space.range_under(self).from_xarray(unlabel_dims(self.matrix.dot(U.array_labeled_as_source())))
    if self.name != self.__class__.__name__: out.name = self.name
    return out

In [ ]:
U1 = S.ones()

In [ ]:
op1.apply(U1)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={B: (array([0, 1]),)}),
    XarrayVectorArrayImpl(
        array([3., 3.]),
        XarrayVectorSpace(coord_data={B: (array([0, 1]),)}),
        _data_dims=['B'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
op1 = XarrayMatrixOperator(np.ones((2, 2)), source={'A': np.arange(2)}, range={'B': np.arange(2)})
U1 = XarrayVectorSpace({'A': np.arange(2), 'C': np.arange(3)}).ones()

In [ ]:
op1.apply(U1)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={B: (array([0, 1]),), C: (array([0, 1, 2]),)}),
    XarrayVectorArrayImpl(
        array([[2., 2., 2.], [2., 2., 2.]]),
        XarrayVectorSpace(coord_data={B: (array([0, 1]),), C: (array([0, 1, 2]),)}),
        _data_dims=['B', 'C'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
op1.apply(U1, method='xarray')

XarrayVectorArray(
    XarrayVectorSpace(coord_data={B: (array([0, 1]),), C: (array([0, 1, 2]),)}),
    XarrayVectorArrayImpl(
        array([[2., 2., 2.], [2., 2., 2.]]),
        XarrayVectorSpace(coord_data={B: (array([0, 1]),), C: (array([0, 1, 2]),)}),
        _data_dims=['B', 'C'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
from pymor.tools.random import new_rng

In [ ]:
with new_rng(42):
    U = op.source.random(extended_coords={'foo': np.arange(2)})
U

XarrayVectorArray(
    XarrayVectorSpace(coord_data={A: (array([0, 1, 2, 3, 4]),)}),
    XarrayVectorArrayImpl(
        array([[0.77395605, 0.85859792, 0.09417735, 0.7611397 , 0.12811363],
               [0.43887844, 0.69736803, 0.97562235, 0.78606431, 0.45038594]]),
        XarrayVectorSpace(coord_data={A: (array([0, 1, 2, 3, 4]),)}),
        _data_dims=['foo', 'A'],
        _extended_coord_data={foo: (array([0, 1]),)}),
    _len=2)

In [ ]:
op.apply(U)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={B: (array([0, 1, 2, 3]),)}),
    XarrayVectorArrayImpl(
        array([[0.12601957, 0.62030984, 0.00597851, 0.8288864 ], [0.44580162, 0.73140252, 0.02101756, 1.17285242]]),
        XarrayVectorSpace(coord_data={B: (array([0, 1, 2, 3]),)}),
        _data_dims=['foo', 'B'],
        _extended_coord_data={foo: (array([0, 1]),)}),
    _len=2)

In [ ]:
xr.testing.assert_allclose(op.apply(U, method='numpy').array, op.apply(U, method='xarray').array)

In [ ]:
from pymor.basic import Parameters

In [ ]:
dof = Coordinates({'dof': ('dof', ['x', 'v'], {'long_name': "Degrees of freedom"})})
space = XarrayVectorSpace(dof)
A = XarrayMatrixOperator(np.array([[0., -1.], [1., 0]]), source=space, range=space)
B = XarrayMatrixOperator(np.array([[0., 0.], [0., 1.]]), source=space, range=space)

operator = LincombOperator(
    [A, B], 
    [
        ExpressionParameterFunctional("w0**2", Parameters({'w0': 1})), 
        ExpressionParameterFunctional("c", Parameters({'c': 1}))
    ]
)
mu = dict(c=.1, w0="sin(t)")
mu = Parameters(dict(c=1, w0=1)).parse(mu)

y = operator.source.from_numpy(np.array([1., 0.]))

operator.apply(y, mu=mu.at_time(t=.1))

XarrayVectorArray(
    XarrayVectorSpace(coord_data={dof: (array(['x', 'v'], dtype='<U1'), {'long_name': 'Degrees of freedom'})}),
    XarrayVectorArrayImpl(
        array([0.        , 0.00996671]),
        XarrayVectorSpace(coord_data={dof: (array(['x', 'v'], dtype='<U1'), {'long_name': 'Degrees of freedom'})}),
        _data_dims=['dof'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
%time operator.apply(y, mu=mu.at_time(t=.1))

CPU times: user 287 μs, sys: 10 μs, total: 297 μs
Wall time: 291 μs


XarrayVectorArray(
    XarrayVectorSpace(coord_data={dof: (array(['x', 'v'], dtype='<U1'), {'long_name': 'Degrees of freedom'})}),
    XarrayVectorArrayImpl(
        array([0.        , 0.00996671]),
        XarrayVectorSpace(coord_data={dof: (array(['x', 'v'], dtype='<U1'), {'long_name': 'Degrees of freedom'})}),
        _data_dims=['dof'],
        _extended_coord_data={}),
    _len=1)

### apply_adjoint -

In [ ]:
#| export
@patch
def apply_adjoint(
    self:XarrayMatrixOperator, 
    V, # `XarrayVectorArray` of vectors to which the operator is applied
    mu=None # The parameter values for which to evaluate the operator
)->XarrayVectorArray: # `XarrayVectorArray` in the source `XarrayVectorSpace`
    """Apply the adjoint of the operator to an `XarrayVectorArray` in the range vector space."""
    return self.H.apply(V, mu=mu)

In [ ]:
V = op.range.zeros({'len': [0]})

In [ ]:
op.source

XarrayVectorSpace(coord_data={A: (array([0, 1, 2, 3, 4]),)})

In [ ]:
op.range

XarrayVectorSpace(coord_data={B: (array([0, 1, 2, 3]),)})

In [ ]:
op.H

Format,coo
Data Type,float64
Shape,"(4, 5)"
nnz,10
Density,0.5
Read-only,True
Size,160
Storage ratio,1.00


In [ ]:
op.H.range

XarrayVectorSpace(coord_data={A: (array([0, 1, 2, 3, 4]), {})})

In [ ]:
V.space.range_under(op.H)

XarrayVectorSpace(coord_data={A: (array([0, 1, 2, 3, 4]), {})})

In [ ]:
op.apply_adjoint(V)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={A: (array([0, 1, 2, 3, 4]), {})}),
    XarrayVectorArrayImpl(
        array([[0., 0., 0., 0., 0.]]),
        XarrayVectorSpace(coord_data={A: (array([0, 1, 2, 3, 4]), {})}),
        _data_dims=['len', 'A'],
        _extended_coord_data={len: ([0],)}),
    _len=1)

### _assemble_lincomb -

In [ ]:
# #| export
# @patch
# def _assemble_lincomb(self:XarrayMatrixOperator, operators, coefficients, identity_shift=0., solver_options=None, name=None):
#     if not all(isinstance(op, XarrayMatrixOperator) for op in operators):
#         return None

#     common_mat_dtype = reduce(np.promote_types,
#                               (op.matrix.dtype for op in operators if hasattr(op, 'matrix')))
#     common_coef_dtype = reduce(np.promote_types, (type(c) for c in coefficients + [identity_shift]))
#     common_dtype = np.promote_types(common_mat_dtype, common_coef_dtype)

#     if coefficients[0] == 1:
#         matrix = operators[0].matrix.astype(common_dtype)
#     else:
#         matrix = operators[0].matrix * coefficients[0]
#         if matrix.dtype != common_dtype:
#             matrix = matrix.astype(common_dtype)

#     for op, c in zip(operators[1:], coefficients[1:]):
#         if c == 1:
#             try:
#                 matrix += op.matrix
#             except NotImplementedError:
#                 matrix = matrix + op.matrix
#         elif c == -1:
#             try:
#                 matrix -= op.matrix
#             except NotImplementedError:
#                 matrix = matrix - op.matrix
#         else:
#             try:
#                 matrix += (op.matrix * c)
#             except NotImplementedError:
#                 matrix = matrix + (op.matrix * c)

#     if identity_shift: raise NotImplementedError

#     return XarrayMatrixOperator(matrix, source=self.source, range=self.range, solver_options=solver_options)

In [ ]:
#| export
@patch
def _assemble_lincomb(self:XarrayMatrixOperator, operators, coefficients, identity_shift=0., name=None):
    if not all(isinstance(op, XarrayMatrixOperator) for op in operators):
        return None

    common_mat_dtype = reduce(np.promote_types,
                              (op.matrix.dtype for op in operators if hasattr(op, 'matrix')))
    common_coef_dtype = reduce(np.promote_types, (type(c) for c in coefficients + [identity_shift]))
    common_dtype = np.promote_types(common_mat_dtype, common_coef_dtype)

    if coefficients[0] == 1:
        matrix = operators[0].matrix.astype(common_dtype)
    else:
        matrix = operators[0].matrix * coefficients[0]
        if matrix.dtype != common_dtype:
            matrix = matrix.astype(common_dtype)

    for op, c in zip(operators[1:], coefficients[1:], strict=True):
        if c == 1:
            try:
                matrix += op.matrix
            except NotImplementedError:
                matrix = matrix + op.matrix
        elif c == -1:
            try:
                matrix -= op.matrix
            except NotImplementedError:
                matrix = matrix - op.matrix
        else:
            try:
                matrix += (op.matrix * c)
            except NotImplementedError:
                matrix = matrix + (op.matrix * c)

    if identity_shift: raise NotImplementedError

    return XarrayMatrixOperator(matrix, source=self.source, range=self.range)

In [ ]:
#| hide
LincombOperator([op, op], [.3, .456]).assemble().matrix.data.todense()

array([[5.88746976e-04, 0.00000000e+00, 5.34212675e-03, 0.00000000e+00,
        7.36159172e-01],
       [4.62409789e-01, 1.74351933e-02, 0.00000000e+00, 0.00000000e+00,
        7.50111939e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        3.52792414e-02],
       [3.02294895e-01, 0.00000000e+00, 3.96729643e-01, 4.66816021e-01,
        0.00000000e+00]])

### to_matrix_XarrayMatrixOperator -


In [ ]:
#| exporti
@match_class(XarrayMatrixOperator)
def to_matrix_XarrayMatrixOperator(self, op):
    """Return the operator as a 2D matrix with stacked range and source dimensions in either `ndarray` or `sparray` format."""
    data = op.matrix.stack(_range=op.labeled_range.coords.dims, _source=op.labeled_source.coords.dims).data
    if isinstance(data, SparseArray): return sparse2d(data)
    return data
    
ToMatrixRules.insert_rule(-1, to_matrix_XarrayMatrixOperator)

In [ ]:
#| hide
to_matrix(op)

<Compressed Sparse Row sparse array of dtype 'float64'
	with 10 stored elements and shape (4, 5)>

In [ ]:
#| export
@patch
def to_numpy(self:XarrayMatrixOperator):
    """Return the operator in dense `ndarray` format."""
    return self.matrix.to_numpy()

The returned numpy array will be of shape $r_1\times \ldots \times r_n \times s_1 \times \ldots \times s_m$ where $r_i$ are the dimensions of the $n$ vector spaces making up the range product vector space, and $s_j$ are the dimensions of the $m$ vector spaces making up the source product vector space.

In [ ]:
op.to_numpy()

array([[7.78765841e-04, 0.00000000e+00, 7.06630522e-03, 0.00000000e+00,
        9.73755519e-01],
       [6.11653160e-01, 2.30624250e-02, 0.00000000e+00, 0.00000000e+00,
        9.92211559e-01],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        4.66656632e-02],
       [3.99860972e-01, 0.00000000e+00, 5.24774660e-01, 6.17481510e-01,
        0.00000000e+00]])

### densify -


In [ ]:
#| exporti
class DensifyRules(RuleTable):
    """|RuleTable| for the :func:`densify` algorithm."""

    def __init__(self):
        super().__init__(use_caching=True)

    @match_class(XarrayMatrixOperator)
    def action_XarrayMatrixOperator(self, op):
        op = self.replace_children(op)
        if op.sparse:
            matrix = op.matrix.copy()
            matrix.data = matrix.data.todense()
            op = op.with_(matrix=matrix)
        return op
    
    @match_class(Model, Operator)
    def action_recurse(self, op):
        return self.replace_children(op)

In [ ]:
#| export
def densify(
    obj:Model|Operator # Object to densify
)->Model|Operator: # Densified object
    """Convert sparse operators to dense."""
    return DensifyRules().apply(obj)

An operator backed by a sparse `DataArray`:

In [ ]:
op.sparse

True

Convert the operator to one backed by a dense `DataArray`:

In [ ]:
densify(op).sparse

False

In [ ]:
#|hide
test_eq(_, False)

## XarrayFunctionalOperator

In [ ]:
#| export
class XarrayFunctionalOperator(XarrayMatrixBasedOperator):
    """An `Operator` described by a `ParameterFunctional` that assembles to a `XarrayMatrixOperator`."""
    
    def __init__(self, functional:ParameterFunctional, range, source):
        self.__auto_init(locals())

    def assemble(self, mu=None): 
        return XarrayMatrixOperator(self.functional.evaluate(mu), range=self.range.dims, source=self.source.dims)

    def apply(self, U:VectorArray, mu=None):
        return self.assemble(mu).apply(U)

    @property
    def size(self):
        return self.matrix.size

In [ ]:
from pymor.basic import GenericParameterFunctional

In [ ]:
func = GenericParameterFunctional(lambda mu: DataArray(np.arange(4).reshape(2, 2)**mu['c'], dims=['A', 'B']), {'c': 1})

In [ ]:
func.evaluate(Mu({'c': 2}))

<xarray.DataArray (A: 2, B: 2)> Size: 32B
array([[0, 1],
       [4, 9]])
Dimensions without coordinates: A, B

In [ ]:
op = XarrayFunctionalOperator(
        GenericParameterFunctional(lambda mu: DataArray(np.arange(4).reshape(2, 2)**mu['c'], dims=['A (source)', 'B (range)']), {'c': 1}),
        range=XarrayVectorSpace({'A': [0, 1]}),
        source=XarrayVectorSpace({'B': [0, 1]}),
    )

In [ ]:
op

XarrayFunctionalOperator(
    GenericParameterFunctional(<function <lambda>>, {c: 1}),
    XarrayVectorSpace(coord_data={A: ([0, 1],)}),
    XarrayVectorSpace(coord_data={B: ([0, 1],)}))

In [ ]:
op.assemble(Mu({'c': 2}))

XarrayMatrixOperator(
    <xarray.DataArray (A (source): 2, B (range): 2)> Size: 32B
    array([[0, 1],
           [4, 9]])
    Dimensions without coordinates: A (source), B (range),
    source=XarrayVectorSpace(coord_data={A: (array([0, 1]),)}),
    range=XarrayVectorSpace(coord_data={B: (array([0, 1]),)}))

## IdentityOperator

In [ ]:
# @patch
# def apply(self:IdentityOperator, U, mu=None):
#     if isinstance(U, XarrayVectorArray):

# space_a = XarrayVectorSpace({'A (source)': np.linspace(0, 1, 2)})
# space_b = XarrayVectorSpace({'B': ['c', 'd', 'e']})

# space_a * space_b

# space

# IdentityOperator(space).source.dims

## SumOperator

In [ ]:
#| export
class SumOperator(Operator):
    """An `Operator` that sums over one or more dimensions of a `XarrayVectorSpace`."""
    
    linear = True
    
    def __init__(
        self, 
        source_coords:Coordinates|dict, # Coordinates to sum over 
        name=None # Operator name
    ):
        self.__auto_init(locals())
        self.source = XarrayVectorSpace(source_coords)
        self.range = XarrayVectorSpace("Sum")

    def assemble(self, mu=None): return self

    def apply(self, U, mu=None):
        U = U.space.range_under(self).from_xarray(U.array.sum(self.source.dims).expand_dims('Sum'))
        if self.name != self.__class__.__name__: U.name = self.name
        return U

    def __mul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([self, other])
        return super().__mul__(other)

    def __rmul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([other, self])
        return super().__mul__(other)

    def __str__(self):
        return f"{self.name if self.name != self.__class__.__name__ else '∑'}{_mapping_str(self)}"

In [ ]:
space = XarrayVectorSpace({'A': [1, 2], 'B': ['a', 'b', 'c']}, name='foo')

In [ ]:
np.random.seed(42)
U = space.from_numpy(np.random.rand(space.dim))

In [ ]:
U.array.A

<xarray.DataArray 'A' (A: 2)> Size: 16B
array([1, 2])
Coordinates:
  * A        (A) int64 16B 1 2

In [ ]:
op = SumOperator(U.array.A)
op

SumOperator(
    <xarray.DataArray 'A' (A: 2)> Size: 16B
    array([1, 2])
    Coordinates:
      * A        (A) int64 16B 1 2)

In [ ]:
op.source

XarrayVectorSpace(coord_data={A: (array([1, 2]), {})}, name='A')

In [ ]:
op.range

XarrayVectorSpace(coord_data={Sum: (['Sum'],)})

In [ ]:
op.apply(U).array

<xarray.DataArray (Sum: 1, B: 3)> Size: 24B
array([[0.9731986 , 1.10673295, 0.88798846]])
Coordinates:
  * Sum      (Sum) <U3 12B 'Sum'
  * B        (B) <U1 12B 'a' 'b' 'c'

## ScaleOperator

In [ ]:
#| export
class ScaleOperator(Operator):
    """A scaling operator for `XarrayVectorSpace`s."""
    
    def __init__(self, array, space=None, name=None):
        if not isinstance(array, DataArray): array = DataArray(array, coords=space.coords, name=name)
        if space is None: space = XarrayVectorSpace(array)
        self.__auto_init(locals())
        self.source = space
        self.range = space

    def assemble(self, mu=None): return self

    def apply(self, U, mu=None):
        U = U * self.array
        if self.name != self.__class__.__name__: U.name = self.name
        return U

    @property
    def display_name(self):
        return self.name if self.name != self.__class__.__name__ else 'S'
    
    def __mul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([self, other])
        return super().__mul__(other)

    def __rmul__(self, other):
        if isinstance(other, Operator):
            return ProductOperator([other, self])
        return super().__mul__(other)

    def __str__(self):
        return f"{self.display_name}{_mapping_str(self)}"

In [ ]:
space = XarrayVectorSpace({'A': [1, 2], 'B': ['a', 'b', 'c']}, name='foo')

In [ ]:
U = space.from_numpy(np.arange(6))

In [ ]:
U.array

<xarray.DataArray (A: 2, B: 3)> Size: 48B
array([[0, 1, 2],
       [3, 4, 5]])
Coordinates:
  * A        (A) int64 16B 1 2
  * B        (B) <U1 12B 'a' 'b' 'c'

In [ ]:
arr = U.array[0].drop_vars('A')
arr

<xarray.DataArray (B: 3)> Size: 24B
array([0, 1, 2])
Coordinates:
  * B        (B) <U1 12B 'a' 'b' 'c'

In [ ]:
scale_op = ScaleOperator(arr, name='bar')
scale_op

ScaleOperator(
    <xarray.DataArray (B: 3)> Size: 24B
    array([0, 1, 2])
    Coordinates:
      * B        (B) <U1 12B 'a' 'b' 'c',
    space=XarrayVectorSpace(coord_data={B: (array(['a', 'b', 'c'], dtype='<U1'), {})}),
    name='bar')

In [ ]:
scale_op.apply(U)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={A: ([1, 2],), B: (['a', 'b', 'c'],)}, name='foo'),
    XarrayVectorArrayImpl(
        array([[ 0,  1,  4], [ 0,  4, 10]]),
        XarrayVectorSpace(coord_data={A: ([1, 2],), B: (['a', 'b', 'c'],)}, name='foo'),
        _data_dims=['A', 'B'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
space.ones().array.data

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
ScaleOperator(space.ones().array.data, space=space)

ScaleOperator(
    <xarray.DataArray (A: 2, B: 3)> Size: 48B
    array([[1., 1., 1.],
           [1., 1., 1.]])
    Coordinates:
      * A        (A) int64 16B 1 2
      * B        (B) <U1 12B 'a' 'b' 'c',
    space=XarrayVectorSpace(coord_data={A: ([1, 2],), B: (['a', 'b', 'c'],)}, name='foo'))

In [ ]:
#| hide
# from pylgs.pymor.example_problems import *

# A, B, C, E = lti_matrices()

# input_space = XarrayVectorSpace({'inputs': ['uniform heating', 'left end heating']}, name='input')

# U = input_space.from_numpy(np.array([.3, .7]))

# U

# matrix=DataArray(B, {'grid': np.linspace(0, 1, 101), 'inputs': U.array.coords['inputs']})

# op = XarrayMatrixOperator(matrix)

# op

# op.apply(U)

# op.range

# op.source

# op.H.source

# op.as_range_array()

# op.as_source_array()

# V=op.range.from_numpy(np.linspace(0, 2, 101))

# op.apply_adjoint(V)

## LincombOperator

In [ ]:
#|export
@patch
def __init__(self:LincombOperator, operators, coefficients, solver=None, name=None):
    assert len(operators) > 0
    assert len(operators) == len(coefficients)
    assert all(isinstance(op, Operator) for op in operators)
    assert all(isinstance(c, (ParameterFunctional, Number)) for c in coefficients)
    # assert all(op.source == operators[0].source for op in operators[1:])
    # assert all(op.range == operators[0].range for op in operators[1:])
    operators = tuple(operators)
    coefficients = tuple(coefficients)

    self.operators = operators
    self.coefficients = coefficients
    self.solver = solver
    self.name = name
    try:
        self.source = max(self.operators, key=lambda o: o.source.ndim).source
        self.range = max(self.operators, key=lambda o: o.range.ndim).range
    except AttributeError:
        self.source = self.operators[0].source
        self.range = self.operators[0].range
    self.linear = all(op.linear for op in operators)


In [ ]:
# #|export
# @match_class(LincombOperator)
# def action_LincombOperator(self, op):
#     op_coefficients = op.evaluate_coefficients(self.mu)
#     res = op_coefficients[0] * self.apply(op.operators[0])
#     for i in range(1, len(op.operators)):
#         res = res + op_coefficients[i] * self.apply(op.operators[i])   

In [ ]:
# a = XarrayMatrixOperator(np.ones([3, 2]), source=space_a, range=space_b)
# b = XarrayMatrixOperator(np.eye(2), source='source a', range='range a')

In [ ]:
# LincombOperator([a, b], [1., 1.])

### _numpy_zero_operator -


In [ ]:
#| export
def _numpy_zero_operator(shape):
    return ZeroOperator(*[NumpyVectorSpace(dim) for dim in shape])

### read_sparse_dataarray -


In [ ]:
#| export
def _read_sparse_dataarray(
    file_name:str|Path, # File name
)->DataArray:
    if not Path(file_name).suffix: file_name = Path(file_name).with_suffix('.mtxn')
    header = []
    with open(file_name, "r") as reader:
        while True:
            line = next(reader)
            if line[0] != "%": break
            header.append(line.strip('%\n '))
    matrix = pd.read_csv(
        file_name,
        sep=r'\s+',
        header=None,
        skiprows=len(header),
        index_col=None,
        engine="c",
        comment='%'
    )
    name = header[0]
    parameters = header[1].split('\t')
    shape = [int(s) for s in header[2].split()]
    coords = {dim: index.split('\t') for dim, index in zip(header[3::2], header[4::2])}
    matrix = sparse([matrix.iloc[:, :-1].T, matrix.iloc[:, -1]], shape=shape)
    return DataArray(matrix, coords, name=name, attrs={'parameters': parameters})

In [ ]:
_read_sparse_dataarray('test')

Format,coo
Data Type,float64
Shape,"(2, 3, 4)"
nnz,2
Density,0.08333333333333333
Read-only,True
Size,64
Storage ratio,0.33


In [ ]:
with importlib.resources.path("pylgs.systems.NaD1_Toy", "Flux.mtxn") as path:
    out = _read_sparse_dataarray(path)
out

Format,coo
Data Type,float64
Shape,"(1, 1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,32
Storage ratio,1.00


### from_file -


In [ ]:
#| export 
@patch(cls_method=True)
@delegates(LincombOperator.__init__)
def from_file(
    cls:LincombOperator, 
    file_name:str|Path, # File name
    **kwargs # Additional arguments are passed to `LincombOperator`.
):
    """Read a `LincombOperator` (list of sparse arrays and corresponding `ExpressionParameterFunctionals`) from a .mtxn file."""
    da = _read_sparse_dataarray(file_name)
    coefficients = [
        ExpressionParameterFunctional(s, {p: 1 for p in da.parameters if p in s}) if da.parameters != [''] else 1
        for s in da.coords[da.dims[0]].data
    ]
    del da.attrs['parameters']
    # return da
    operators = [XarrayMatrixOperator(d.drop_vars(da.dims[0])) for d in da]    
    return LincombOperator(operators, coefficients, **kwargs)

In [ ]:
with importlib.resources.path("pylgs.systems.NaD1_Toy", "b.mtxn") as path:
    op = LincombOperator.from_file(path)
op

Format,coo
Data Type,float64
Shape,"(4, 1)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [ ]:
op.as_range_array(Mu({'BeamTransitRatePerS': 1}))

XarrayVectorArray(
    XarrayVectorSpace(
        coord_data={Density matrix: (array(['ρ<sub>Re, 3S<sub>1/2</sub>, 3S<sub>1/2</sub></sub>',
                           'ρ<sub>Re, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                           'ρ<sub>Im, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                           'ρ<sub>Re, 3P<sub>1/2</sub>, 3P<sub>1/2</sub></sub>'], dtype='<U50'), {})}),
    XarrayVectorArrayImpl(
        array([1., 0., 0., 0.]),
        XarrayVectorSpace(
            coord_data={Density matrix: (array(['ρ<sub>Re, 3S<sub>1/2</sub>, 3S<sub>1/2</sub></sub>',
                               'ρ<sub>Re, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                               'ρ<sub>Im, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                               'ρ<sub>Re, 3P<sub>1/2</sub>, 3P<sub>1/2</sub></sub>'], dtype='<U50'), {})}),
        _data_dims=['Density matrix'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
with importlib.resources.path("pylgs.systems.NaD1_Toy", "Flux.mtxn") as path:
    op = LincombOperator.from_file(path)
op

Format,coo
Data Type,float64
Shape,"(1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [ ]:
op.source

XarrayVectorSpace(
    coord_data={Density matrix: (array(['ρ<sub>Re, 3S<sub>1/2</sub>, 3S<sub>1/2</sub></sub>',
                       'ρ<sub>Re, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                       'ρ<sub>Im, 3S<sub>1/2</sub>, 3P<sub>1/2</sub></sub>',
                       'ρ<sub>Re, 3P<sub>1/2</sub>, 3P<sub>1/2</sub></sub>'], dtype='<U50'), {})})

In [ ]:
op.range

XarrayVectorSpace(coord_data={})

In [ ]:
op.assemble()

Format,coo
Data Type,float64
Shape,"(1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [ ]:
# op = LincombOperator.from_file('test.mtxn')
# op

### partial_evaluate -


In [ ]:
#| export 
@patch
def partial_evaluate(
    self:ExpressionParameterFunctional, 
    mu:dict|Mu # Parameter values 
)->float|ExpressionParameterFunctional:
    """Substitute parameter values, returning a new `ExpressionParameterFunctional` if expression does not evaluate to a number."""
    mu = {k: v[0] for k, v in mu.items()}
    expr = sy.sympify(self.expression).subs(mu)
    unevaluated = [str(s) for s in expr.free_symbols]
    if expr.is_number:
        return float(expr)
    return ExpressionParameterFunctional(
        str(expr), 
        {k: v for k, v in self.parameters.items() if k in unevaluated}
    )

In [ ]:
# op.coefficients[1].partial_evaluate({'A': [.5]})

In [ ]:
# op.coefficients[1].partial_evaluate({'A': [.5], 'B': [2.]})

### partial_evaluate_coefficients -


In [ ]:
#| export 
@patch
def partial_evaluate_coefficients(
    self:LincombOperator, 
    mu:Mu # Parameter values to substitute
):
    """Substitute parameter values into linear coefficients, returning a new `ExpressionParameterFunctional` if expression does not evaluate to a number."""
    result = []
    for c in self.coefficients:
        try:
            result.append(c.evaluate(mu))
        except AttributeError:
            result.append(c)
        except AssertionError:
            try:
                result.append(c.partial_evaluate(mu))
            except Exception as e:
                result.append(c)
    return result

In [ ]:
# op.partial_evaluate_coefficients(Mu({'A': .5}))

### partial_assemble -

In [ ]:
#| export 
@patch
def partial_assemble(
    self:LincombOperator, 
    mu=None # Parameter values to substitute
)->Operator:
    """Substitute parameter values into the linear coefficients, returning a new operator with fewer (or no) parameters."""
    operators = tuple(op.assemble(mu) for op in self.operators)
    coefficients = self.partial_evaluate_coefficients(mu)
    evaluated = [[], []]
    unevaluated = [[], []]
    for o, c in zip(operators, coefficients):
        if isinstance(c, Number):
            if c:
                evaluated[0].append(o)
                evaluated[1].append(c)
        else:
            unevaluated[0].append(o)
            unevaluated[1].append(c)
    op = []
    if len(evaluated[0]):
        op.append(assemble_lincomb(
            *evaluated, 
            # solver_options=self.solver_options,
            name=self.name + '_partially_assembled'
        ))
    if len(unevaluated[0]):
        op.append(LincombOperator(*unevaluated))
    if len(op) == 0:
        op = [ZeroOperator(range=self.range, source=self.source)]
    op = np.sum(op)
    # To avoid infinite recursions, only use the result if at least one of the following
    # is true:
    #   - The operator is parametric, so the the result of assemble *must* be a different,
    #     non-parametric operator.
    #   - One of self.operators changed by calling 'assemble' on it.
    #   - The result of assemble_lincomb is of a different type than the original operator.
    #   - assemble_lincomb could simplify the list of assembled operators,
    #     which we define to be the case when the number of operators has ben reduced.
    if (self.parametric
            or operators != self.operators  # for this comparison to work self.operators always has to be a tuple!
            or type(op) != type(self)
            or len(op.operators) < len(operators)):
        return op
    else:
        return self

In [ ]:
op

Format,coo
Data Type,float64
Shape,"(1, 4)"
nnz,1
Density,0.25
Read-only,True
Size,24
Storage ratio,0.75


In [ ]:
# op.partial_assemble(Mu({'A': .5}))

In [ ]:
# op.partial_assemble(Mu({'A': .5, 'B': 2.}))

In [ ]:
# op.partial_assemble(Mu({'A': 0}))

### terms -


In [ ]:
#| export
@patch(as_prop=True)
def terms(self:LincombOperator):
    return [c * o for c, o in zip(self.coefficients, self.operators)]

In [ ]:
# #| export
# @patch
# def scalar_part(self:LincombOperator, mu):
#     mu_vector = Mu({k: v for k, v in mu.items() if v.size > 1})
#     return np.sum([o for o in self.terms if not set(mu_vector).intersection(o.parameters)])

In [ ]:
# #| export
# @patch
# def vector_part(self:LincombOperator, mu):
#     mu_vector = Mu({k: v for k, v in mu.items() if v.size > 1})
#     return np.sum([o for o in self.terms if set(mu_vector).intersection(o.parameters)])

## ProductOperator

In [ ]:
#| export 
class ProductOperator(Operator):
    """An Operator given by the direct product of operators `operators`."""
    
    suboperator_symbol = '⛒'
    
    def __init__(
        self, 
        operators, # Sequence of operators that each assemble to XarrayMatrixOperator
        name=None, # Optional name
    ):
        for op in operators:
            if not isinstance(op, Operator): raise ValueError(f'Input {op} should be an Operator.')
        self.source = np.prod([op.source for op in operators])
        self.range = np.prod([op.range for op in operators])
        self.__auto_init(locals())
        self.linear = True
        
    def apply(self, U, mu=None):
        pass

In [ ]:
A = XarrayMatrixOperator(array([[1, 0], [0, 1]]), source={'source a': [0, 1]}, range={'range a': [0, 1]})
B = XarrayMatrixOperator(array([[0, 1], [1, 0]]), source={'source b': [0, 1]}, range={'range b': [0, 1]})

In [ ]:
#| export
@patch
def __mul__(self:Operator, other):
    if isinstance(other, Operator) and all(isinstance(space, XarrayVectorSpace) for space in [self.source, self.range, other.source, other.range]):
        return ProductOperator([self, other])
    if isinstance(other, (Number, ParameterFunctional)):
        if self.name != 'LincombOperator' or not isinstance(self, LincombOperator):
            return LincombOperator((self,), (other,))
        else:
            return self.with_(coefficients=tuple(c * other for c in self.coefficients))
    else:
        raise TypeError(f'Object {other} is not an Operator, Number, or ParameterFunctional.')

In [ ]:
#| export
@patch
def __str__(self:ProductOperator):
    return ' ⨂ '.join(str(o) for o in self.operators)

In [ ]:
#| export
@patch
def __str__(self:IdentityOperator):
    return f'I{_mapping_str(self)}'

In [ ]:
A * IdentityOperator(B.source)

ProductOperator(
    [XarrayMatrixOperator(
         <xarray.DataArray (range a (range): 2, source a (source): 2)> Size: 32B
         array([[1, 0],
                [0, 1]])
         Coordinates:
           * range a (range)    (range a (range)) int64 16B 0 1
           * source a (source)  (source a (source)) int64 16B 0 1,
         source=XarrayVectorSpace(coord_data={source a: ([0, 1],)}),
         range=XarrayVectorSpace(coord_data={range a: ([0, 1],)})),
     IdentityOperator(XarrayVectorSpace(coord_data={source b: ([0, 1],)}))])

In [ ]:
IdentityOperator(B.source) * A

ProductOperator(
    [IdentityOperator(XarrayVectorSpace(coord_data={source b: ([0, 1],)})),
     XarrayMatrixOperator(
         <xarray.DataArray (range a (range): 2, source a (source): 2)> Size: 32B
         array([[1, 0],
                [0, 1]])
         Coordinates:
           * range a (range)    (range a (range)) int64 16B 0 1
           * source a (source)  (source a (source)) int64 16B 0 1,
         source=XarrayVectorSpace(coord_data={source a: ([0, 1],)}),
         range=XarrayVectorSpace(coord_data={range a: ([0, 1],)}))])

In [ ]:
def vec(a):
    return a.T.ravel()

In [ ]:
s=1

In [ ]:
A = XarrayMatrixOperator(
    sparse2d_rand([3*s, 2*s], density=.1, random_state=42), 
    source={'source a': np.arange(2*s)}, 
    range={'range a': np.arange(3*s)}
)
A

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33


In [ ]:
mu = Mu(A=.5)

In [ ]:
B = ExpressionParameterFunctional('A**2', {'A': 1}) * XarrayMatrixOperator(
    sparse2d_rand([4*s, 5*s], density=.1, random_state=42),
    source={'source b': np.arange(5*s)}, 
    range={'range b': np.arange(4*s)}
)
B = B.assemble(mu)

In [ ]:
op = A * B
op

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33
Format,coo
Data Type,float64
Shape,"(4, 5)"


In [ ]:
op.source

XarrayVectorSpace(coord_data={source a: (array([0, 1]),), source b: (array([0, 1, 2, 3, 4]), {})})

In [ ]:
op.range

XarrayVectorSpace(coord_data={range a: (array([0, 1, 2]),), range b: (array([0, 1, 2, 3]), {})})

In [ ]:
B.source._array

<xarray.DataArray 'XarrayVectorSpace' (source b: 5)> Size: 40B
array([0., 0., 0., 0., 0.])
Coordinates:
  * source b  (source b) int64 40B 0 1 2 3 4

In [ ]:
sum_op = SumOperator(B.source._array['source b'])

In [ ]:
sum_op * A

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33


In [ ]:
A * sum_op

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33


In [ ]:
np.random.seed(42)
U = op.source.from_numpy(np.random.rand(op.source._array.size))
V = op.range.from_numpy(np.random.rand(op.range._array.size))

In [ ]:
U.space

XarrayVectorSpace(coord_data={source a: (array([0, 1]),), source b: (array([0, 1, 2, 3, 4]), {})})

In [ ]:
An = A.matrix.data
Bn = B.assemble(mu).matrix.data
Un = U.to_numpy().T
Vn = V.to_numpy().T

In [ ]:
%%time 
An = A.matrix.data
Bn = B.assemble(mu).matrix.data
Un = U.to_numpy().T
out1 = np.kron(An, Bn).dot(vec(Un))

CPU times: user 95.9 ms, sys: 3.01 ms, total: 98.9 ms
Wall time: 98.2 ms


In [ ]:
%%time
An = A.matrix.data
Bn = B.assemble(mu).matrix.data
Un = U.array.T.data
out3 = An.dot(Bn.dot(Un).T).ravel()

CPU times: user 685 μs, sys: 35 μs, total: 720 μs
Wall time: 704 μs


In [ ]:
B.apply(U)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={source a: (array([0, 1]),), range b: (array([0, 1, 2, 3]), {})}),
    XarrayVectorArrayImpl(
        array([[7.29197627e-05, 3.87008746e-02, 0.00000000e+00, 0.00000000e+00],
               [3.03708010e-05, 1.75639449e-01, 0.00000000e+00, 0.00000000e+00]]),
        XarrayVectorSpace(coord_data={source a: (array([0, 1]),), range b: (array([0, 1, 2, 3]), {})}),
        _data_dims=['source a', 'range b'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
%%time
out4 = A.apply(B.apply(U)).to_numpy()

CPU times: user 685 μs, sys: 33 μs, total: 718 μs
Wall time: 700 μs


In [ ]:
test_close(out1.ravel(), out3.ravel())
test_close(out1.ravel(), out4.ravel())

In [ ]:
test_close(
    np.kron(An, Bn).dot(vec(Un)),
    An.dot(Bn.dot(Un).T).ravel()
)

 N.B.: `to_numpy` on a `NumpyVectorArray` effectively takes the transpose.

### apply -


In [ ]:
#| export 
@patch
def apply(self:ProductOperator, U, mu=None):
    U = U.copy()
    for op in self.operators[::-1]:
        U = op.assemble(mu).apply(U)
    return U.space.range_under(self).from_xarray(U.array)

In [ ]:
W = space.from_numpy(np.arange(12), extended_coord_data='len')

In [ ]:
C = ScaleOperator(W.array[0, 0].drop_vars(['A', 'len']), name='C')
C.apply(W).name

'C'

In [ ]:
#| hide
test_eq(_, 'C')

In [ ]:
D = SumOperator(W.array.A, name='D')
D.apply(W).name

'D'

In [ ]:
#| hide
test_eq(_, 'D')

In [ ]:
C = ScaleOperator(W.array[0, 0].drop_vars(['A', 'len']))
E = (C * D)
E.apply(W).name

'XarrayVectorArray'

In [ ]:
E.name

'ProductOperator'

In [ ]:
#| hide
# test_eq(_, 'D')

In [ ]:
E = C * (C * D)
E.apply(W).array.name

In [ ]:
#| hide
# test_eq(_, 'D')

In [ ]:
%%time 
K = A * B.assemble(mu)
out2 = K.apply(U).to_numpy()

CPU times: user 1.16 ms, sys: 76 μs, total: 1.24 ms
Wall time: 1.19 ms


In [ ]:
# test_close(out1.ravel(), out2.ravel())

In [ ]:
test_close(
    op.apply(U, mu).to_numpy().ravel(), 
    np.kron(An, Bn).dot(vec(Un))
)

$(A\bigotimes B)^T=A^T\bigotimes B^T$

In [ ]:
test_close(np.kron(An, Bn).T, np.kron(An.T, Bn.T))

In [ ]:
C = XarrayMatrixOperator(np.ones([2, 2]), source='A', range='A')
D = XarrayMatrixOperator(np.ones([3, 3]), source='B', range='B')

In [ ]:
U1 = (C * D).source.ones()

In [ ]:
op1 = C + C * D

In [ ]:
op1

LincombOperator(
    (XarrayMatrixOperator(
         <xarray.DataArray (A (range): 2, A (source): 2)> Size: 32B
         array([[1., 1.],
                [1., 1.]])
         Coordinates:
           * A (range)   (A (range)) int64 16B 0 1
           * A (source)  (A (source)) int64 16B 0 1,
         source=XarrayVectorSpace(coord_data={A: (array([0, 1]),)}),
         range=XarrayVectorSpace(coord_data={A: (array([0, 1]),)})),
     ProductOperator(
         [XarrayMatrixOperator(
              <xarray.DataArray (A (range): 2, A (source): 2)> Size: 32B
              array([[1., 1.],
                     [1., 1.]])
              Coordinates:
                * A (range)   (A (range)) int64 16B 0 1
                * A (source)  (A (source)) int64 16B 0 1,
              source=XarrayVectorSpace(coord_data={A: (array([0, 1]),)}),
              range=XarrayVectorSpace(coord_data={A: (array([0, 1]),)})),
          XarrayMatrixOperator(
              <xarray.DataArray (B (range): 3, B (source): 3)> Size: 72B
              array([[1., 1., 1.],
                     [1., 1., 1.],
                     [1., 1., 1.]])
              Coordinates:
                * B (range)   (B (range)) int64 24B 0 1 2
                * B (source)  (B (source)) int64 24B 0 1 2,
              source=XarrayVectorSpace(coord_data={B: (array([0, 1, 2]),)}),
              range=XarrayVectorSpace(coord_data={B: (array([0, 1, 2]),)}))])),
    (1.0, 1.0))

In [ ]:
C.apply(U1)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
    XarrayVectorArrayImpl(
        array([[2., 2., 2.], [2., 2., 2.]]),
        XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
        _data_dims=['A', 'B'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
D.apply(U1)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
    XarrayVectorArrayImpl(
        array([[3., 3., 3.], [3., 3., 3.]]),
        XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
        _data_dims=['A', 'B'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
(C * D).apply(U1)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
    XarrayVectorArrayImpl(
        array([[6., 6., 6.], [6., 6., 6.]]),
        XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
        _data_dims=['A', 'B'],
        _extended_coord_data={}),
    _len=1)

In [ ]:
(C + (C * D)).apply(U1)

XarrayVectorArray(
    XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
    XarrayVectorArrayImpl(
        array([[8., 8., 8.], [8., 8., 8.]]),
        XarrayVectorSpace(coord_data={A: (array([0, 1]),), B: (array([0, 1, 2]),)}),
        _data_dims=['A', 'B'],
        _extended_coord_data={}),
    _len=1)

### H -


In [ ]:
#| export 
@patch(as_prop=True)
def H(self:ProductOperator):
    return self.with_(operators=[op.H for op in self.operators])

In [ ]:
op.H

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33
Format,coo
Data Type,float64
Shape,"(4, 5)"


$\text{vec}(V)(A\bigotimes B)=(A\bigotimes B)^T\text{vec}(V)$.

In [ ]:
op.H.source

XarrayVectorSpace(coord_data={range a: (array([0, 1, 2]), {}), range b: (array([0, 1, 2, 3]), {})})

In [ ]:
test_close(
    vec(Vn).dot(np.kron(An, Bn).todense()),
    (np.kron(An, Bn).T).dot(vec(Vn))
)

### apply_adjoint -


In [ ]:
#| export 
@patch
def apply_adjoint(self:ProductOperator, V, mu=None):
    return self.H.apply(V, mu=mu)

In [ ]:
test_close(
    op.apply_adjoint(V, mu).to_numpy().ravel(),
    vec(Vn).dot(np.kron(An, Bn).todense())
)

### assemble -


In [ ]:
#| export 
@patch
def assemble(self:ProductOperator, mu=None):
    operators = [op.assemble(mu) for op in self.operators]
    if any(isinstance(op, ZeroOperator) for op in operators): return ZeroOperator(self.range, self.source)
    if all(op == old_op for op, old_op in zip(operators, self.operators)): return self 
    return self.with_(operators=operators)

In [ ]:
op.assemble(mu)

Format,coo
Data Type,float64
Shape,"(3, 2)"
nnz,1
Density,0.16666666666666666
Read-only,True
Size,16
Storage ratio,0.33
Format,coo
Data Type,float64
Shape,"(4, 5)"


In [ ]:
zero = (0 * B).assemble()

In [ ]:
(A * zero).assemble()

ZeroOperator(
    XarrayVectorSpace(coord_data={range a: (array([0, 1, 2]),), range b: (array([0, 1, 2, 3]), {})}),
    XarrayVectorSpace(coord_data={source a: (array([0, 1]),), source b: (array([0, 1, 2, 3, 4]), {})}))

### expand_ProductOperator -


In [ ]:
#| exporti
@match_class(ProductOperator)
def expand_ProductOperator(self, op):
    op = self.replace_children(op)

    # merge child ProductOperators
    if any(isinstance(o, ProductOperator) for o in op.operators):
        ops = []
        for o in op.operators:
            if isinstance(o, ProductOperator):
                ops.extend(o.operators)
            else:
                ops.append(o)
        op = op.with_(operators=ops)

    # expand products with LincombOperators
    if any(isinstance(o, LincombOperator) for o in op.operators):
        i = next(iter(i for i, o in enumerate(op.operators) if isinstance(o, LincombOperator)))
        left, right = op.operators[:i], op.operators[i+1:]
        ops = [ProductOperator([*left, o, *right]) for o in op.operators[i].operators]
        op = op.operators[i].with_(operators=ops)

        # there can still be LincombOperators within the summands so we recurse ..
        op = self.apply(op)
    return op

#| export
ExpandRules.insert_rule(-1, expand_ProductOperator)

In [ ]:
#| exporti
@match_class(IdentityOperator)
def expand_IdentityOperator(self, op):
    if not isinstance(op.source, XarrayVectorSpace): return op
    return ProductOperator([IdentityOperator(XarrayVectorSpace({k:v})) for k,v in op.space.coord_data.items()])

#| export
ExpandRules.insert_rule(-1, expand_IdentityOperator)

In [ ]:
ProductOperator([IdentityOperator(XarrayVectorSpace({k:v})) for k,v in space.coord_data.items()])

ProductOperator(
    [IdentityOperator(XarrayVectorSpace(coord_data={A: ([1, 2],)})),
     IdentityOperator(XarrayVectorSpace(coord_data={B: (['a', 'b', 'c'],)}))])

In [ ]:
expand(IdentityOperator(space))

ProductOperator(
    [IdentityOperator(XarrayVectorSpace(coord_data={A: ([1, 2],)})),
     IdentityOperator(XarrayVectorSpace(coord_data={B: (['a', 'b', 'c'],)}))])

### contract_ProductOperator -


In [ ]:
#| exporti
@match_class(ProductOperator)
def contract_ProductOperator(self, op):
    op = self.replace_children(op)
    if any(isinstance(o, ZeroOperator) for o in op.operators): return ZeroOperator(op.range, op.source)
    xarray_operators = [o for o in op.operators if     isinstance(o, XarrayMatrixOperator)]
    other_operators  = [o for o in op.operators if not isinstance(o, XarrayMatrixOperator)]
    if xarray_operators:
        matrices, ranges, sources = unzip([(o.matrix, o.range, o.source) for o in xarray_operators])
        op = XarrayMatrixOperator(
            math.prod(matrices), 
            source=math.prod(sources, start=XarrayVectorSpace()), 
            range=math.prod(ranges, start=XarrayVectorSpace())
        )
    else:
        op = 1
    if other_operators:
        op *= math.prod(other_operators) 
    return op

ContractRules.insert_rule(-2, contract_ProductOperator)

In [ ]:
#| hide
contract(op)

Format,coo
Data Type,float64
Shape,"(3, 2, 4, 5)"
nnz,2
Density,0.016666666666666666
Read-only,True
Size,80
Storage ratio,0.08


### to_matrix -

In [ ]:
# #| hide
# #| exporti
# @match_class(ProductOperator)
# def to_matrix_ProductOperator(self, op):
#     return self.apply(contract(op))
    
# ToMatrixRules.insert_rule(-2, to_matrix_ProductOperator)

In [ ]:
# #| hide
# to_matrix(op, mu=mu)

In [ ]:
#| hide
#| exporti
@match_class(ProductOperator)
def to_matrix_ProductOperator(self, op):
    return kron(*[self.apply(o) for o in op.operators])
    
ToMatrixRules.insert_rule(-2, to_matrix_ProductOperator)

In [ ]:
to_matrix(op, mu=mu)

<Compressed Sparse Row sparse array of dtype 'float64'
	with 2 stored elements and shape (12, 10)>

In [ ]:
test_array('operators', 'to_matrix_ProductOperator_1', _.todense())

In [ ]:
op1 = densify(op.operators[0]) * op.operators[1]

In [ ]:
to_matrix(op1, mu=mu)

<Compressed Sparse Row sparse array of dtype 'float64'
	with 2 stored elements and shape (12, 10)>

In [ ]:
test_array('operators', 'to_matrix_ProductOperator_1', _.todense())

### as_source_array -


In [ ]:
#| export 
@patch
def as_source_array(self:ProductOperator, mu=None):
    return contract(self.assemble(mu)).as_source_array()

In [ ]:
# op.as_source_array(mu)

In [ ]:
# test_close(
#     np.kron(An, Bn).todense().ravel(),
#     op.as_source_array(mu).to_numpy().T.ravel()
# )

### as_range_array -


In [ ]:
#| export 
@patch
def as_range_array(self:ProductOperator, mu=None):
    return contract(self.assemble(mu)).as_range_array()

In [ ]:
# test_close(
#     np.kron(An, Bn).todense().ravel(),
#     op.as_range_array(mu).to_numpy().ravel()
# )

## Export -

In [ ]:
#| hide
import nbdev; nbdev.nbdev_export()