In [59]:
#| default_exp velocitygroups

# velocitygroups
> Create and manipulate a list of bins of the atomic velocity distribution for use in the LGS model

## Imports -

In [60]:
#| hide
from fastcore.test import test_close

In [61]:
#| export
from pylgs.imports import *
from pylgs.utilities.nbdev import DictTbl, AttributeTbl
from pylgs.utilities.testing import test_array
from pylgs.utilities.sparse import sparse_kronecker_matrix, sparse_toeplitz, sparse_identity, sparse_diag, sparse
from pylgs.utilities.numpy import sym_range
from pylgs.pymor.parameters import *
from pylgs.pymor.vectorarrays import *
from pylgs.pymor.operators import *
from pylgs.pymor.grids import *
from pymor.vectorarrays.interface import VectorArray
from pymor.operators.interface import Operator
from pymor.basic import IdentityOperator

In [62]:
#| hide
np.set_printoptions(formatter={'float': lambda x: f'{x:^ 8.2}' if x else f'{0:^ 8}'}, linewidth=140)

## Velocity groups -

In [63]:
from numbers import Number

In [64]:
#| export
class VelocityGroups(dict):
    """`VelocityGroups` contains informations about the centers, edges, and relative densities of a list of velocity group bins."""
    def __init__(self, 
                 bins:Iterable|int=6, # Iterable of velocity group edges or int specifying number of evenly spaced velocity groups
                 range:Number|Iterable=3 # Default range (`min_vel`, `max_vel`) or half-width `max_vel` for velocity groups
                ):
        super().__init__()
        if isinstance(bins, VelocityGroups):
            self.edges = bins.edges
            for k, v in bins.items():
                self[k] = v
            return
        if isinstance(range, Number): range = (-range, range)
        self.edges = np.linspace(*range, bins + 1) if isinstance(bins, int) else bins
        self['VGCenter'] = np.mean(np.array(list(zip(self.edges[:-1], self.edges[1:]))), axis=1)
        # self['VGBins'] = np.array(list(zip(bins[:-1], bins[1:])))
        # self['VGCenter'] = np.mean(self['VGBins'], axis=1)
        self['VGDensity'] = np.diff(erf(self.edges))/2
        self['VGWidth'] = np.diff(self.edges)
        # self['VGEdges'] = bins
        self['VGInverseWidth'] = 1/self['VGWidth']
        self['VGNumber'] = len(self['VGCenter'])
        self['velocity_groups'] = np.ones(self['VGDensity'].shape)

Create a list of two evenly spaced velocity groups:

In [65]:
vg = VelocityGroups(2)
vg

{'VGCenter': array([  -1.5  ,    1.5  ]),
 'VGDensity': array([   0.5  ,    0.5  ]),
 'VGWidth': array([   3.0  ,    3.0  ]),
 'VGInverseWidth': array([  0.33  ,   0.33  ]),
 'VGNumber': 2,
 'velocity_groups': array([   1.0  ,    1.0  ])}

### subdivide -


In [66]:
#| export
@patch
def subdivide(
    self:VelocityGroups, 
    indices:int|ndarray|slice=slice(None), # Indices, boolean array, or slice object specifying velocity groups to subdivide
    n:int=2 # Number of groups to subdivide into
):
    """Divide the velocity groups with indices `indices` in two."""
    new_edges = np.concat([np.linspace(c - w/2, c + w/2, n + 1)[1:-1] for c,w in zip(self["VGCenter"][indices], self["VGWidth"][indices])])
    return VelocityGroups(np.union1d(self.edges, new_edges))

Return a new `VelocityGroups` object with the groups at index 1 divided in two:

In [67]:
vg.subdivide([1]).subdivide([1, 2])

{'VGCenter': array([  -1.5  ,   0.38  ,    1.1  ,    1.9  ,    2.6  ]),
 'VGDensity': array([   0.5  ,   0.36  ,   0.13  ,   0.016 ,  0.00072]),
 'VGWidth': array([   3.0  ,   0.75  ,   0.75  ,   0.75  ,   0.75  ]),
 'VGInverseWidth': array([  0.33  ,    1.3  ,    1.3  ,    1.3  ,    1.3  ]),
 'VGNumber': 5,
 'velocity_groups': array([   1.0  ,    1.0  ,    1.0  ,    1.0  ,    1.0  ])}

In [68]:
vg.subdivide([1], n=4)

{'VGCenter': array([  -1.5  ,   0.38  ,    1.1  ,    1.9  ,    2.6  ]),
 'VGDensity': array([   0.5  ,   0.36  ,   0.13  ,   0.016 ,  0.00072]),
 'VGWidth': array([   3.0  ,   0.75  ,   0.75  ,   0.75  ,   0.75  ]),
 'VGInverseWidth': array([  0.33  ,    1.3  ,    1.3  ,    1.3  ,    1.3  ]),
 'VGNumber': 5,
 'velocity_groups': array([   1.0  ,    1.0  ,    1.0  ,    1.0  ,    1.0  ])}

### _velocity_space -


In [69]:
#| export
def _velocity_space(vg, ext=''):
    return XarrayVectorSpace({'Atomic velocity' + ext: vg['VGCenter']})

### _vg_identity -

In [70]:
#| export
def _vg_identity(vg):
    return XarrayMatrixOperator(
        DataArray(sparse_identity(vg['VGNumber']), coords=[('Atomic velocity' + Lbl.RNG, vg['VGCenter']), ('Atomic velocity', vg['VGCenter'])])
    )

### _vg_diagonal -

In [71]:
#| hide
ScaleOperator(vg['VGCenter'], space=_velocity_space(vg))

ScaleOperator(
    <xarray.DataArray (Atomic velocity: 2)> Size: 16B
    array([  -1.5  ,    1.5  ])
    Coordinates:
      * Atomic velocity  (Atomic velocity) float64 16B -1.5 1.5,
    space=XarrayVectorSpace(coord_data={Atomic velocity: (array([  -1.5  ,    1.5  ]),)}))

### identity -

In [72]:
#| export
@patch
def identity(self:VelocityGroups)->Operator:
    """The velocity-space identity operator."""
    return IdentityOperator(_velocity_space(self))
    # return XarrayMatrixOperator(
    #         sparse_identity(self['VGNumber']), 
    #         range=_velocity_space(self), 
    #         source=_velocity_space(self)
    #     )

In [73]:
vg.identity()

IdentityOperator(XarrayVectorSpace(coord_data={Atomic velocity: (array([  -1.5  ,    1.5  ]),)}))

In [74]:
# _.to_numpy()

In [75]:
#| hide
# test_array('core', 'VelocityGroups_identity', _)

### velocity_diagonal -

In [76]:
#| export
def _vg_diagonal(vg, diags):
    return XarrayMatrixOperator(
        DataArray(sparse_diag(diags), coords=[('Atomic velocity' + Lbl.RNG, vg['VGCenter']), ('Atomic velocity' + Lbl.SRC, vg['VGCenter'])])
    )

In [77]:
#| export
@patch
def velocity_diagonal(self:VelocityGroups)->Operator:
    """A velocity-space operator with the velocity on the diagonal."""
    return _vg_diagonal(self, self['VGCenter'])

In [78]:
vg.velocity_diagonal()

Format,coo
Data Type,float64
Shape,"(2, 2)"
nnz,2
Density,0.5
Read-only,True
Size,32
Storage ratio,1.00


In [79]:
_.to_numpy()

array([[  -1.5  ,     0   ],
       [    0   ,    1.5  ]])

In [80]:
#| hide
test_array('core', 'VelocityGroups_velocity_digonal', _)

### velocity_density_vector -

In [81]:
#| export
def velocity_density_vector(vg):
    return _velocity_space(vg).from_numpy(vg['VGDensity'])

### n_times_1 -

In [82]:
#| export
@patch
def n_times_1(self:VelocityGroups)->Operator:
    """Operator that sums over all velocity groups then scales by the Maxwell-Boltzmann distribution."""
    return XarrayMatrixOperator(
        sparse(self['VGDensity'][:, None] * np.ones((self['VGNumber']))),
        range=_velocity_space(self), 
        source=_velocity_space(self)
    )

In [83]:
vg.n_times_1()

Format,coo
Data Type,float64
Shape,"(2, 2)"
nnz,4
Density,1.0
Read-only,True
Size,96
Storage ratio,3.00


In [84]:
_.to_numpy()

array([[   0.5  ,    0.5  ],
       [   0.5  ,    0.5  ]])

In [85]:
#| hide
test_array('core', 'VelocityGroups_n_times_1', _)

In [86]:
#| hide
# This is really a product operator of velocity_sum followed by velocity_maxwell. Should refactor
test_close(_, (_velocity_space(vg).ones() * velocity_density_vector(vg)).array.data)

### drho_dv -

In [87]:
#| export
@patch
def drho_dv(self:VelocityGroups)->Operator:
    """Derivative with respect to velocity operator.$"""
    return XarrayMatrixOperator(
        self['VGInverseWidth'] * (sparse_kronecker_matrix(self['VGNumber'], 0) - sparse_kronecker_matrix(self['VGNumber'], -1)), 
        range=_velocity_space(self), 
        source=_velocity_space(self)
    )

In [88]:
vg.drho_dv() 

Format,coo
Data Type,float64
Shape,"(2, 2)"
nnz,3
Density,0.75
Read-only,True
Size,48
Storage ratio,1.50


In [89]:
_.to_numpy()

array([[  0.33  ,     0   ],
       [ -0.33  ,   0.33  ]])

In [90]:
#| hide
test_array('core', 'VelocityGroups_drho_dv', _)

In [91]:
#| hide
vg.drho_dv().matrix.sel({'Atomic velocity' + Lbl.RNG: 1.5, 'Atomic velocity' + Lbl.SRC: -1.5}).data.item()

-0.3333333333333333

### _vg_da -


In [92]:
#| export
def _vg_da(a, vg):
    range = ('Atomic velocity' + Lbl.RNG, vg['VGCenter']) if a.shape[0] == vg['VGNumber'] else ("none", ["none"])
    source = ('Atomic velocity' + Lbl.SRC, vg['VGCenter']) if a.shape[1] == vg['VGNumber'] else ("none", ["none"])
    return DataArray(a, coords=[range, source])

### normalize -


In [93]:
#| export
@patch
def normalize(self:VelocityGroups)->Operator:
    """Returns the operator that normalizes a vector by dividing each component by the width of the corresponding velocity group."""
    return ScaleOperator(DataArray(self['VGInverseWidth'], {'Atomic velocity': self['VGCenter']}))

In [94]:
vg.normalize()

ScaleOperator(
    <xarray.DataArray (Atomic velocity: 2)> Size: 16B
    array([  0.33  ,   0.33  ])
    Coordinates:
      * Atomic velocity  (Atomic velocity) float64 16B -1.5 1.5,
    space=XarrayVectorSpace(coord_data={Atomic velocity: (array([  -1.5  ,    1.5  ]), {})}))

### sum -


In [95]:
#| export
@patch
def sum(self:VelocityGroups)->Operator:
    """Returns the operator that sums a vector over velocity groups."""
    return SumOperator({'Atomic velocity': self['VGCenter']})

In [96]:
vg.sum()

SumOperator({Atomic velocity: array([  -1.5  ,    1.5  ])})

## Export -

In [98]:
#| hide
import nbdev; nbdev.nbdev_export()